### ISSUE TITLE
HeatMode works on Google Home app, but not on Google Nest Hub

### ISSUE THREAD

**Issue by kandersen01** [openhab/openhab-google-assistant#104]
I´m not really sure if this is an openhab issue at all, or perhaps a Google issue.

I have been running Google Assistant for long, and thermostat heatmode is running fine in the Google Home App. After I got myself  a Google Nest Hub (Home Hub), when entering one of my thermostats, Google Nest Home respond with that the heatingmode isnt supported. Ligts and other devices (from openhab) is working great. Just heatingmode seems to have an issue.

**Comment by goofy1988** [comment]
Same Issue here.

**Comment by kandersen01** [comment]
This has been fixed after 2.0 was deployed.

**Comment by marziman** [comment]
Closing
