### ISSUE TITLE
Blinds still inverted

### ISSUE THREAD

**Issue by scavenrage** [openhab/openhab-google-assistant#105]
Hi,
I'm sorry that maybe this is an already closed issue, but I've read all the threads without finding a solution.
I have a rolleshutter item

Rollershutter TapTest "Target Tapparella TEST [%.0f %%]" <blinds> [ "Blinds" ] {mqtt="<[broker:CasaRage/camera/taptest/ftapparella:state:default],>[broker:CasaRage/camera/taptest/ftapparella:command:*:default]"}

This item works correctly with openhab and the basic UI. If I set it to 100% the rolleshutter will completely close itself and if I set it to 0% it will open.

When I ask to Google Assistant, for example "set the rollershutter to 55%" the item receive 45%, when i set 0% the item receive 100%, etc.
In the example here I asked "set Taptest to 55%", and here is the log

[INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'TapTest' received command 45.

I've tried to add the tags
googleassistant="shutter" [ direction="UpDown", invert=true, percent=true ]
in the items definition (also with "DownUp" or with invert=false) but nothing changes.
Thanks for your help

**Comment by Stefan300381** [comment]
Same issue on my side "hey google, set blinds to 55%" ends up in my scenario to MQTT command:
`shellies/shellyswitch25-5D98C1/roller/0/command/pos 45`

I'm running OH 2.5 M2

**Comment by Stefan300381** [comment]
@scavenrage I found out that even a command "DOWN" (e.g. via button in HABPanel) will lead to value 100 being sent. So maybe the issue is not openHAB?

**Comment by scavenrage** [comment]
Some hardware are configured with 0% open, 100% closed, others with 0% closed and 100% open. The issue is not on openhab but in the connection between Google and openhab. Because when I ask it to "set the blind to 75%", it answer "ok i OPEN the blind to 75%". So technically it's correct to send the value "25". But it's very confusing to use Google and openhab together because the percentage is inverted from one to another. I understand that @pythen tried to resolve the issue by inserting tags in the items but in my version they didn't work (maybe I have to change some files or configuration with the new provided by him)

**Comment by Stefan300381** [comment]
I tried the invert as well, no change

**Comment by scavenrage** [comment]
Interesting,
to resolve the problem I implemented some rules instead.
Can you explain how do you implemented the javascript transformation? Thanks!

**Comment by Stefan300381** [comment]
likes this:

mqtt.thing extract:
`Type rollershutter : control    "control"       [ stateTopic="shellies/shellyswitch25-5D98C1/roller/0/pos", commandTopic="shellies/shellyswitch25-5D98C1/roller/0/command/pos", transformationPattern="JS:InvertPercent.js", transformationPatternOut="JS:InvertPercent.js"  ]`

transform/InvertPercent.js
```
(function(i) {
        // shelly 0 = Closed / 100 = open
        // oh2 UP cmnd = 0 / DOWN cmnd = 100

        //The following script converts [0% - 100%] to  [100% - 0%].
        var percent_shelly = parseInt(i, 10);

        var percent_oh = (100.0 - percent_shelly);

        //Return result with one decimal accuracy
        return percent_oh.toFixed(0);
})(input)
```

**Comment by marziman** [comment]
Is this still relevant?

**Comment by michikrug** [comment]
With the merged metadata support you can state if the values should be inverted

**Comment by scavenrage** [comment]
> With the merged metadata support you can state if the values should be inverted

Thanks, can you give me an example?

**Comment by scavenrage** [comment]
ok sorry, I've just see that the documentation was updated yesterday with all the information. I'll give a try as soon as possible!

**Comment by scavenrage** [comment]
Just updated to openhab 2.5, tried to add the metadata but doesn't work (google does not recognize the item).
There is something specific to update to add the merged metadata support?
thanks

**Comment by michikrug** [comment]
I assume @marziman first needs to deploy the recent changes before they can be used. He will hopefully do an announcement as soon as its live.

**Comment by scavenrage** [comment]
Thank you very much for your work =)
