### ISSUE TITLE
Unable to control

### ISSUE THREAD

**Issue by fabiofolino** [openhab/openhab-google-assistant#12]
I'm not on the official beta test but I was able to setup a test action and get the Google Home linked to myopenhab.org account. When I've tried to turn a light on or off GH responds with, "I'm sorry, there was an error. I'm unable to control your home device."

I'm using the userpass option to connect. 

Here are the logs.

`D      openhabGoogleAssistant  aagk7mrfh2z2  2017-11-08 00:47:32.649  Function execution started
I      openhabGoogleAssistant  aagk7mrfh2z2  2017-11-08 00:47:32.752  openhabGoogleAssistant: Cloud function called:{"inputs":[{"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"customData":{"itemTag":"Lighting","itemType":"Switch","openhabVersion":"2.1"},"id":"Light_GF_Corner_Lamp"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":false}}]}]}}],"requestId":"6561282519311464578"}
I      openhabGoogleAssistant  aagk7mrfh2z2  2017-11-08 00:47:32.753  openhabGoogleAssistant - turnOnOff reqCommand:{"devices":[{"customData":{"itemTag":"Lighting","itemType":"Switch","openhabVersion":"2.1"},"id":"Light_GF_Corner_Lamp"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":false}}]}
E      openhabGoogleAssistant  aagk7mrfh2z2  2017-11-08 00:47:33.736  openhabGoogleAssistant - turnOnOff failed: Error response 404
D      openhabGoogleAssistant  aagk7mrfh2z2  2017-11-08 00:47:33.738  Function execution took 1090 ms, finished with status code: 500
`

**Comment by fabiofolino** [comment]
Solved..

In config.js its important to have a trailing slash on the path.

 path: '/rest/items/'

**Comment by sk8ter** [comment]
Hello fabiofolino. Could you please explain what steps have you done to get the Google Home linked to myopenhab.org account? Hoes it require to install own instance of myopenhab cloud?

**Comment by fabiofolino** [comment]
Mostly follow the instructions in the docs to setup the google. You do not
necessarily need a cloud account, but you do have to open up access to your
openhab api to the web. I chose to use the cloud.

The main thing in the functions/config.js file you have to change the
settings to whatever you choose.

You'll have to play around with OAuth on the actions page. I ended up using
https://accounts.google.com/o/oauth2/v2/auth and
https://www.googleapis.com/oauth2/v4/token, but it required some further
updating of the allowed redirects in the console.

Hope that makes sense.
