### ISSUE TITLE
commands executed but assistant answers "sorry i can't reach ...."

### ISSUE THREAD

**Issue by costascontis** [openhab/openhab-google-assistant#121]
I use my Google homes a lot because my inability to use my hands.I turn on and off lights and other switchable devices a lot every day using GA and openhab.I noticed about a month ago that giving a command ,this command executed right but GA answers "Sorry i can't reach X device right now ,please try again later.This is very annoying to hear and i cant know for sure that the command is done unless i go check if i am not in the same room.Is this gonna be fixed somehow?Is it google's fault or openhab's.Do i need to change something in my system?

**Comment by Dopeyr** [comment]
Hi, keep an eye on https://github.com/openhab/openhab-google-assistant/pull/118 which has a fix for this issue.

**Comment by costascontis** [comment]
> Hi, keep an eye on #118 which has a fix for this issue.

i see that #118 is merged now.So do i need to do something in my system for the fix to apply?

**Comment by Dopeyr** [comment]
Do you use myopenhab.org? If so, I believe it's being rolled out this weekend: https://community.openhab.org/t/openhab-google-assistant-integration-v2-0/85573

**Comment by marziman** [comment]
fixed by https://github.com/openhab/openhab-google-assistant/pull/118
