### ISSUE TITLE
Implement Camera / CameraStream

### ISSUE THREAD

**Issue by xdanik** [openhab/openhab-google-assistant#122]
Would be please possible to add support for Camera device type?
https://developers.google.com/assistant/smarthome/guides/camera.html
https://developers.google.com/assistant/smarthome/traits/camerastream.html

It seems simple - just publish existing camera feed URL to Google.
Of course the user will have to make sure the feed is in the supported format 😉

**Comment by michikrug** [comment]
What kind of openHAB item would you link to this?

**Comment by xdanik** [comment]
Maybe just an string item containing the camera feed?

**Comment by michikrug** [comment]
Could probably implement it like this.
I would a bit struggle with: `cameraStreamSupportedProtocols`

**Comment by michikrug** [comment]
With the metadata update, we could add a configuration option to specify the support protocol on the item.

**Comment by michikrug** [comment]
https://github.com/openhab/openhab-google-assistant/pull/120/commits/3345594246d28f079ef0bfe33f593a0587b02e8b

**Comment by xdanik** [comment]
Wow, that was quick. I said it should be simple 😂
Thanks!
I look forward to trying it out.

**Comment by marziman** [comment]
Thanks @michikrug
