### ISSUE TITLE
Implement Garage Door

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-google-assistant#123]
Please implement the Garage Door device type (https://developers.google.com/assistant/smarthome/guides/garage.html).

**Comment by robnielsen** [comment]
It appears that the Door device type is almost identical

**Comment by michikrug** [comment]
It is now available. Use the tag "Garage".

**Comment by robnielsen** [comment]
Good news, I'll give it a try

**Comment by marziman** [comment]
Will be done with https://github.com/openhab/openhab-google-assistant/pull/120
by @michikrug 
Rollout this week.
