### ISSUE TITLE
Feature Request: Support setting color-temperature for (RGB)W lights

### ISSUE THREAD

**Issue by sesuncedu** [openhab/openhab-google-assistant#125]
This is a bit tricky to handle due to limitations in openhab's ontology, but it might be possible to use a similar hack to the way thermostats are being handled, with a group tagged as Lighting containing a Color item plus a dimmer or a Number for the color temperature.

The upper and lower bounds of the Colour temperature would probably have to be hand coded in the metadata, since there doesn't seem to be a  generic way to communicate them from the device even if the handler knows them.

**Comment by michikrug** [comment]
I added support for color temperature in form of an automated color calculation (Kelvin temperature is converted to HSB values):
https://github.com/openhab/openhab-google-assistant/pull/120/commits/2eb73c7a4624fdcde57175fc3c72ec8b8d5dd180

**Comment by marziman** [comment]
I think this is solved.
