### ISSUE TITLE
Feature request: implement air purifier

### ISSUE THREAD

**Issue by thomasjacumin666** [openhab/openhab-google-assistant#128]
Hello,
Is it possible to implement AIRPURIFIER device?(https://developers.google.com/assistant/smarthome/guides/airpurifier)

Thanks in advance for your answer. :)

**Comment by michikrug** [comment]
What would be your items on openHAB for controlling it?

**Comment by thomasjacumin666** [comment]
I think it is useful to implement only the OnOff trait (Switch item).

**Comment by michikrug** [comment]
So there is no special need for the specific device type? Just use the Switchable tag (or later the switch metadata).

I think it would only make sense if we also support the modes trait.
But then it would be interesting to know how people use it on the openhab side to implement the proper "translation".

**Comment by thomasjacumin666** [comment]
Actually I just wanted a nicer icon in the Google home app than the switchable one. :)

But maybe it is possible to use Group item for the air purifier, with Switch for the OnOff trait, Number for the mode trait, like thermostat device?

**Comment by thomasjacumin666** [comment]
Actually I just wanted a nicer icon in the Google home app than the switchable one. :)

But maybe it is possible to use Group item for the air purifier, with Switch for the OnOff trait, Number for the mode trait, like thermostat device?

**Comment by michikrug** [comment]
Added the AirPurifier type for Switch and Dimmer items, works currently the same as FAN (OnOff & FanSpeed trait).

*NOT published, only implemented in the metadata PR.*

And yes, the modes trait would require some kind of group as the thermostats.

**Comment by marziman** [comment]
Done with https://github.com/openhab/openhab-google-assistant/pull/120
by @michikrug 
Will be deployed this week.
