### ISSUE TITLE
Issues with Dimmer functionality for dimmable light switch

### ISSUE THREAD

**Issue by adiun** [openhab/openhab-google-assistant#129]
I am running Openhab 2.5 through Openhabian. I have two Dimmer items:

* Dimmer item associated with 5 IKEA Tradfri dimmable lightbulbs
* Dimmer item associated with a Z-Wave HomeSeer dimmable light switch

When I associate the "Lighting" tag with these items, I can add them in the Google Home app but they just show up as normal lights with ON/OFF - no dimmer UI. If I send a voice command like "turn on [item label]", a little slider UI pops up in the Google Assistant app that seems to allow me to change the brightness, but there's no actual change. 

If I go through the OpenHAB PaperUI, I'm able to control the brightness of these items.

Is there something I'm doing wrong here? Should I be associating a different kind of tag? I thought the item type (Dimmer) would have been enough.

**Comment by michikrug** [comment]
Should also be resolved.
