### ISSUE TITLE
Group of rollershutter issue

### ISSUE THREAD

**Issue by dirkpitt74** [openhab/openhab-google-assistant#135]
Hi,
In the last two weeks I have encountered some problems with the Rollershutter Groups.
I have configured some groups of shutters in this way on the items file

`Group:Rolleshutter  g_Balconi  "Balconi" {ga = "Blinds" `}`

`Rollershutter  F_Cucina  "Finestra Cucina"  (g_Balconi)  { ga="Blinds" channel=....}`
`Rollershutter  F_Sala  "Finestra Sala"  (g_Balconi)  { ga="Blinds" channel=....}`

When I ask Google to close/open "Finestra Cucina" or "Finestra Sala" Openhab recieve the right command "UP"/"DOWN" but when I ask  close/open "Balconi" Openhab recieve the command "ON"/"OFF".

On Google Home app the "Balconi" object is correctly recognized as blinds but Openhab recieve a wrong command.

I can solve this problem using a dummy rollershutter object followed by a rule to manage the state but this is an new unexpected behavior and I wanted to report it.

Thanks

**Comment by michikrug** [comment]
Thanks for reporting. I will investigate on that.

**Comment by michikrug** [comment]
Just for later reference: should be fixed with https://github.com/openhab/openhab-google-assistant/commit/1c7209514f5350da299b5095e7f4c517b8ad13f3

**Comment by michikrug** [comment]
Should be fixed now
