### ISSUE TITLE
Synonyms metadata option should be synonym

### ISSUE THREAD

**Issue by mstroeve** [openhab/openhab-google-assistant#137]
I tried to add more than one synonym (one works fine btw) with synonyms="term1,term2" tag. But this doesn't seem to work. 

The binding source code seems to split on the , character in devices.js "item.metadata.synonyms.value.split(',')". 

But on the Google API side It only seem to accept one (string)?:

_nickname | stringNickname for this device specified by, which would be used for speech recognition and device targeting when user speaks to a device, e.g., user can say "move my smart robot left" when she has a device named "my smart robot"._

Maybe it's better to clarify  this in the docs? 
Or rename tthis meta option to synonym?

**Comment by michikrug** [comment]
Well, the docs on the Google Actions page say:
`nicknames: Array<String>. Optional. Additional names provided by the user for the device.`

(https://developers.google.com/assistant/smarthome/develop/process-intents#SYNC)

So it should be implemented correctly. Although, I have not tested multiple synonyms so far.

Where do you got your definition from?

**Comment by mstroeve** [comment]
You're right I just google it and it seems to have led me to a older version of the api docs. 
 Maybe it's a language issue. It's not a really big problem. For most devices 1 synonym would be sufficient (we already have the primary name also).

Hmm no problem I wil try it again with some other terms. And if not I will close this issue for now.

**Comment by michikrug** [comment]
As there was an implementation issue that was fixed in fall last year, I will close this.
