### ISSUE TITLE
Support color temperature for non-RGB lights

### ISSUE THREAD

**Issue by kabili207** [openhab/openhab-google-assistant#138]
I have several Tradfri bulbs that are only have cool white and warm white LEDs. Since there are no RGB LEDs, these expose two `Dimmer` channels instead of a `Color` channel: one for brightness and one for color temperature.

The only way I can see to make these bulbs work would be to use a group to combine the two channels similar to what is done with thermostats.

**Comment by michikrug** [comment]
You could use a `Color` item (shared with Google) and translate its value to your two `Dimmer` items using rules.

**Comment by DjSni** [comment]
with phillips hue it is the same behaviour

**Comment by AudiTTR** [comment]
Yes, it's the same with Hue colour temperature bulbs (0x220).  Native Hue integration with Google works fine, i.e. you get the colour button below the brightness control in Google Home so you can change the colour temperature of the bulb with Google. However, for Hue bulbs that are integrated with Google via OpenHAB, you don't get the colour button below the brightness control in Google Home.  Therefore, you're not able to control the colour temperature of Hue bulbs that are integrated via OpenHAB with Google Home; you can only control the brightness.  Is there a way to configure your .items files in OH2 so that Google Home shows these bulbs with the colour 
button as well as the brightness control?

Example of a Hue colour temp bulb (0x220) integrated with Google Home via the native Hue app; notice you can change the brightness & the colour temperature:
![IMG-8451](https://user-images.githubusercontent.com/60132059/91782130-9aa7bb80-ec3f-11ea-9618-95224de952a6.PNG)

Example of a Hue colour temp bulb (0x220) integrated with Google Home via OpenHAB; notice you can only change the brightness but not the colour temperature:
![IMG-8452](https://user-images.githubusercontent.com/60132059/91782216-d93d7600-ec3f-11ea-82a0-433d104f9a6d.PNG)

**Comment by michikrug** [comment]
So I assume the add-on still provides two Dimmer items for each bulb?
If so, there is currently no easy way to expose this to Google for color control, as it would require a `Color` item.

As I stated it already you could use a `Color` item (exposed to Google) and translate its value to your two Dimmer items using custom rules (will require some calculation).


Btw. what value is the `Dimmer` item for the color temperature reflecting? Is there a special mapping?

**Comment by michikrug** [comment]
I already build some similar logic to convert color temperature here:
https://github.com/openhab/openhab-google-assistant/blob/master/functions/commands.js#L360

**Comment by kabili207** [comment]
The `ColorSetting` trait requires `temperatureMinK` and `temperatureMaxK` when using color temperature. This can easily be mapped to a percentage value. Users would need to supply these values since each bulb could be different (my Hue bulbs are 2000 to 6500 and my Tradfris are 2200 to 4000). Although we could supply some sane default values.

I tried mapping everything to a color channel in the past and it really didn't work very well. Going from Kelvin to RGB was simple enough, but going from RGB to Kelvin while accounting for brightness was a mess that never worked right. It was more user friendly for me to expose the raw `Dimmer` values to Google instead. Having proper support for color temperature bulbs would be a great improvement.

**Comment by michikrug** [comment]
Well there is proper support, but the openHAB addons and/or APIs provided by the companies building the bulbs are not nicely compatible with Google's API. (e.g. having a percentage value for color temperature - which is just "stupid")

**Comment by kabili207** [comment]
Having looked at a few of the addons, some of them could definitely be mapped to a color temperature value. [Zigbee](https://github.com/openhab/org.openhab.binding.zigbee/blob/master/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/internal/converter/ZigBeeConverterColorTemperature.java#L251) has access the actual min/max temperatures, which it uses for it's percentage calculation, and [Tradfri](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriColor.java#L152) uses the CIE color coordinate system, which could be converted back and forth relatively easily. [Philips Hue](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java#L154), on the other hand, seems to use some random min/max values with no clear link to actual color temp values (which is just lazy since it runs on the Zigbee protocol).

Supporting `Number` items for color temperature would make sense at the bare minimum, but the only thing that really changes is that the conversion to and from percentage is eliminated. Users would still need to supply the min and max values. I already have intermediary items using transforms to go from percent to number and back, so this wouldn't be a major issue for me. We would also still need to have a group to combine brightness and color temp since they are two independent channels.

Ideally, openHAB would have a `ColorTemp` item type that would handle the min and max values. This would also have the benefit of being more intuitive in the various user interfaces (paper UI, android app, etc.).

**Comment by michikrug** [comment]
Sooo. I did it and implemented a "SpecialColorLight" that can work with two Dimmer items.
Stay tuned...

**Comment by AudiTTR** [comment]
> So I assume the add-on still provides two Dimmer items for each bulb?

Yes, that's correct - 2 dimmer items and no colour controls :-(

> If so, there is currently no easy way to expose this to Google for color control, as it would require a `Color` item.

There must be a way if the native Hue app can identify the bulbs as Colour Temperature bulbs and not Colour bulbs.  Notice the colour selection panel in the 1st screenshot above only displays 6 colour temperatures to choose from.  Whereas if it was a Colour bulb, then the colour panel has a much wider range of colour choices.  Therefore, there must be a flag or metadata that the native Hue app passes over to Google to identify the bulb as a Colour Temperature bulb vs a Colour bulb.
> 
> As I stated it already you could use a `Color` item (exposed to Google) and translate its value to your two Dimmer items using custom rules (will require some calculation).
> 
> Btw. what value is the `Dimmer` item for the color temperature reflecting? Is there a special mapping?
> [EDIT]
> Found it:
> 
> > color_temperature | Dimmer | This channel supports adjusting the color temperature from cold (0%) to warm (100%).
> 
> So even the direct usage with Google would not be possible, as Google would provide color temperature as a kelvin value. There would still be the translation to percentage missing.

A good starting point would be to get Google to only display the 6 colour temperatures, instead of nothing at all (i.e. only brightness).  If that works, then it should be simple enough (I hope) to translate each of the 6 Google colour temps values into an appropriate colour temp % via a rule in OH2.

**Comment by AudiTTR** [comment]
Here's how each 0220 (colour temp) bulb is identified in the OH2 .items file
```
Switch    pDownstairsHall_Lights_OnOff    "On/Off [%s]"    <light>    (gDownstairs_Hall) {channel="hue:0220:raspbeebridge:downstairs-hall-lights:switch"}
Dimmer    pDownstairsHall_Lights_Brightness    "Brightness [%d %%]"    <slider>    (gDownstairs_Hall) {channel="hue:0220:raspbeebridge:downstairs-hall-lights:brightness", ga="Light" [name="Downstairs Hall lights", roomHint="Downstairs Hall"]}
Dimmer    pDownstairsHall_Lights_ColourTemp    "Colour Temperature [%d]"    <heating>    (gDownstairs_Hall) {channel="hue:0220:raspbeebridge:downstairs-hall-lights:color_temperature"} 
```
So what we really need is some way to identify the 2nd dimmer item (which is used to control the colour_temperature channel in OH2) to Google as a colour temperature control, AND, link the 2nd dimmer item to the 1st dimmer item (for brightness control) so that Google sees these 2 items as a single colour temp bulb, and that way both brightness and colour temp can be controlled for that bulb from within Google.

Something like this - just making it up to illustrate the problem - I'm sure there's a more elegant way to do it:
```
Switch    pDownstairsHall_Lights_OnOff    "On/Off [%s]"    <light>    (gDownstairs_Hall) {channel="hue:0220:raspbeebridge:downstairs-hall-lights:switch"}
Dimmer    pDownstairsHall_Lights_Brightness    "Brightness [%d %%]"    <slider>    (gDownstairs_Hall) {channel="hue:0220:raspbeebridge:downstairs-hall-lights:brightness", ga="Light" [name="Downstairs Hall lights", roomHint="Downstairs Hall"]}
Dimmer    pDownstairsHall_Lights_ColourTemp    "Colour Temperature [%d]"    <heating>    (gDownstairs_Hall) {channel="hue:0220:raspbeebridge:downstairs-hall-lights:color_temperature", ga="ColourTemperature" [name="Downstairs Hall lights, roomHint="Downstairs Hall"]} 
```

**Comment by michikrug** [comment]
In my test setup it now looks like that:
```
Group ColorLight "Farblampe" { ga="light" [ colorTemperatureRange="2000,9000" ] }
Dimmer ColorLightB "Helligkeit" (ColorLight) { ga="lightBrightness" }
Dimmer ColorLightT "Temperatur" (ColorLight) { ga="lightColorTemperature" }
```

and results in:
![Screenshot_20200902-105705](https://user-images.githubusercontent.com/727517/91961789-f3448a80-ed0b-11ea-81e7-2b263db56fb1.jpg)

**Comment by kabili207** [comment]
Nice and simple. I like it. My only questions would be whether it would make more sense to have the `colorTemperatureRange` on the `lightColorTemperature` item or not.

**Comment by michikrug** [comment]
So far I always implemented configuration options on the "main" item. (Which sometimes caused confusion, but it is at least very consistent.)

**Comment by kabili207** [comment]
Ah, it would probably cause more confusion if you broke the norm then. Consistency is always key in my opinion.

**Comment by AudiTTR** [comment]
@michikrug: that looks elegant and simple - i.e. create a Group item in OH2 which is exposed to Google as a Colour Temp bulb 👍

Will this feature be available in a future release of the Google Assistant Binding for OH2, or will it only be available in the GA binding for OH3?

**Comment by michikrug** [comment]
I am totally unaware of any release plans of openhab. But from my pov I would say it should be integrated in the current version.

**Comment by AudiTTR** [comment]
@michikrug: so this feature will be available soon, whenever the next stable release of the GA binding is ready?

**Comment by michikrug** [comment]
As I am just contributing here and have no responsibility for releasing, we always depend on @marziman for such things.

**Comment by AudiTTR** [comment]
Hi @michikrug:  How did you get the above (https://github.com/openhab/openhab-google-assistant/issues/138#issuecomment-685462152) to work in your test setup?  Are you running the latest 2.5.9 snapshot build on your test setup?   I am running 2.5.7-1 release build

**Comment by michikrug** [comment]
I run my own setup with my development code.

**Comment by catsoo** [comment]
@michikrug - thanks for adding `SpecialColorLight`. 

I would have one minor request to actually cover all cases for this one. As noted above ZigBee Devices expose color temperature in the native format also supported by Google Assistant directly (i.e. Kelvin 0-9000 with min/max). I actually integrated the Tradfi Lights using a generic ZigBee Gateway and get a Dimmer (for Brightness, this work great) and a Number for color temperature. 

Can we add a config switch to support setting temperature natively as directly supported by Google Assistant. I image this could be done by adding a flag `useKelvin` - like shown below. One could default to a 0-100 Dimmer though I'm not sure which version is more prevalent. Would be a bit silly if we'd end up converting from Kelvin to % to Kelvin if both end support the native format.

```
Group ColorLight "Farblampe" { ga="light" [ colorTemperatureRange="2000,9000", useKelvin=true ] }
Dimmer ColorLightB "Helligkeit" (ColorLight) { ga="lightBrightness" }
Number ColorLightT "Temperatur" (ColorLight) { ga="lightColorTemperature" }
```

**Comment by michikrug** [comment]
Very valid point. I will probably add it like you described. :)

**Comment by michikrug** [comment]
`useKelvin` support added in [`98c56b2` (#175)](https://github.com/openhab/openhab-google-assistant/pull/175/commits/98c56b20811569b3d0090d923705a16d230d961a)

**Comment by cholawo** [comment]
@michikrug I attempted to implement this and I notice that my Light group wasn't being picked up.   Looks like `colorTemperatureRange` has to be present for it to work, but that's not shown in the readme which says

> Group { ga="Light" [ useKelvin=true ] } (Light with separate brightness and color items)

If that's correct, can you add that colorTemperatureRange to the docs?

**Comment by michikrug** [comment]
> @michikrug I attempted to implement this and I notice that my Light group wasn't being picked up. Looks like `colorTemperatureRange` has to be present for it to work, but that's not shown in the readme which says
> 
> > Group { ga="Light" [ useKelvin=true ] } (Light with separate brightness and color items)
> 
> If that's correct, can you add that colorTemperatureRange to the docs?

That is correct.
I will either add this to the documentation or think about making it optional when `useKelvin` is set.

**Comment by michikrug** [comment]
Did both

**Comment by Rapti** [comment]
This looks great. Do you think you can extend this to also support RGBW lights, both with a fixed and controllable white temperature?
