### ISSUE TITLE
thermostatMode modes not restrictable

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-google-assistant#139]
In the documentation of the binding it says

> (Mandatory) Mode: Number (Zwave THERMOSTAT_MODE Format) or String (off, heat, cool, on, ...). { ga="thermostatMode" }
**you can define the supported modes with the config option [ modes="on,off,heat,cool" ]**

I have the following item definitions:

> Group g_EG_Schlafen_Klimaanlage "Schlafzimmer Klimaanlage" <climate> [ "Thermostat" ] { ga="Thermostat", alexa="Endpoint.Thermostat" }

> Number:Temperature EG_Schlafen_Klimaanlage_Temperatur_Aktuell "Aktuelle Temperatur [%.1f °C]" (g_EG_Schlafen_Klimaanlage) [ "CurrentTemperature" ] { ga="thermostatTemperatureAmbient", alexa="TemperatureSensor.temperature" }

> Number:Temperature EG_Schlafen_Klimaanlage_Temperatur_Ziel "Eingestellte Temperatur [%.1f °C]" (g_EG_Schlafen_Klimaanlage) [ "homekit:TargetTemperature" ] { ga="thermostatTemperatureSetpoint", alexa="ThermostatController.targetSetpoint" }

> String EG_Schlafen_Klimaanlage_Modus "Betriebsmodus" (g_EG_Schlafen_Klimaanlage) [ "homekit:TargetHeatingCoolingMode", "homekit:CurrentHeatingCoolingMode" ] { **ga="thermostatMode" [ modes="on,off,heat,cool" ]**, alexa="ThermostatController.thermostatMode" [OFF="off",HEAT="heat",COOL="cool",AUTO="on"]}

But the Google Home App still shows all modes (e.g. heatcool, which is not supported by my hardware). I would expect it to report the modes given. Am I doing something wrong or is this a bug?

**Comment by michikrug** [comment]
The documentation is probably misleading or not precise enough... :(

The modes have to be also defined on the thermostat item.


As a rule of thumb: currently, all config options are always attached to the grouping item

**Comment by eikowagenknecht** [comment]
Thank you, that did the trick :-)

The config also has an error in the following lines:

(Optional) **Humidity** Setpoint High: Number. { ga="thermostat**Temperature**SetpointHigh" }
(Optional) **Humidity** Setpoint Low: Number. { ga="thermostat**Temperature**SetpointLow" }

I'll try to create a PR to fix this in the next few days and clarify on the modes thing.
