### ISSUE TITLE
[Feature Request] Make use of tags optional

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-google-assistant#142]
In my setup, I use all three: Amazon Alexa, Google Assistant and Apple HomeKit.

I'd like to be able to configure which items to use in which assistant. In the old bindings that was not possible at all because they all relied on the same tags.

PR #120 goes a long way to enabling this (use of dedicated ga=*** metadata). But as stated there:

> Former supported tags will continue to work - but no additional functionality will be supported.

I would very much like this to be optional so that I can choose not to use the shared tags in this binding.

Probably a not-so-common use case, so some obscure command line setting would be fine for me (as long as it's documented).

What do you think?

**Comment by michikrug** [comment]
Since this is not a binding, there is no way (at least no proper way) to tell the integration to not use tags by the user. So I assume home kit is the leftover one still relying on tags?

**Comment by eikowagenknecht** [comment]
You are correct, the optimal solution would be to overhaul the home kit integration. But since that is not happening anytime soon as far as I can see, it would be nice to have the possibility in the assistant integration to ignore the tags and only use the new metadata notation.

**Comment by eikowagenknecht** [comment]
Just a quick update (and close): The homekit integration has recently been changed so this is not an issue any more.
