### ISSUE TITLE
Add availableArmLevels attribute to SecuritySystem ArmDisarm trait

### ISSUE THREAD

**Issue by Jzooor** [openhab/openhab-google-assistant#146]
I would like to propose an enhancement to the SecuritySystem device to add support for setting available arm levels on the ArmDisarm trait.

https://developers.google.com/assistant/smarthome/traits/armdisarm

It should be possible to command different security system arm levels. For example my system can be armed AWAY or STAY (as well as disarmed). 

I envision being able to do something similar to the following in the metadata: 
`{ ga="SecuritySystem" [ levels="0=disarm:off,1=stay:armed stay,2=away:armed away", lang="en", ordered=true ] }`

**Comment by duanemck** [comment]
I'm working on adding this functionality, I am most of the way there, just testing in my actual setup to ensure it covers most all the use cases I can think of. It will depend on PR #175 to be merged first.

I would like to make a few other quality of life improvements too, like being able to only required the PIN when disarming but not arming.

**Comment by SeveranExp** [comment]
> I'm working on adding this functionality, I am most of the way there, just testing in my actual setup to ensure it covers most all the use cases I can think of. It will depend on PR #175 to be merged first.
> 
> I would like to make a few other quality of life improvements too, like being able to only required the PIN when disarming but not arming.

I’ve been looking at this since January. I’ve created feature request that expands on this (exceptions) but this topic is pretty important because without defining mode we can’t trigger routines that arm the security system from google home.

let me know if you need testers!!

**Comment by duanemck** [comment]
> > I'm working on adding this functionality, I am most of the way there, just testing in my actual setup to ensure it covers most all the use cases I can think of. It will depend on PR #175 to be merged first.
> > I would like to make a few other quality of life improvements too, like being able to only required the PIN when disarming but not arming.
> 
> I’ve been looking at this since January. I’ve created feature request that expands on this (exceptions) but this topic is pretty important because without defining mode we can’t trigger routines that arm the security system from google home.
> 
> let me know if you need testers!!

Sorry, I need to get back to this. I had some issues rebasing off the new develop branch after the refactoring PR (#175 ) and I then got distracted. I'll try get it into it again this weekend.

**Comment by duanemck** [comment]
Can probably also me close with #226
