### ISSUE TITLE
Thermostat Group does not work

### ISSUE THREAD

**Issue by janwo** [openhab/openhab-google-assistant#147]
Hi guys
unfortunately I can`t get my thermostat configuration running using the Spirit Eutronic Thermostat (Manual: https://community.openhab.org/t/eurotronic-spirit-unsupported-mode-type-31/57265/32).

The state of FF_Bedroom_Heater_Mode is `"state": "1"`. However the mapping to `auto` does not work. In Google Home it shows the correct ambient temperature and 'Heizen' / 'Heat'.  I cannot control the temperature as it shows no controls. Any ideas?

These are my items:
````

Group   gFF_Bedroom_Heater             (gHeatingManagement_Thermostat, gFF_Bedroom) { ga="Thermostat" [ modes="off=0,heat=15,auto=1,eco=11" ] }
Number  FF_Bedroom_Heater_Mode         (gFF_Bedroom_Heater, gHeatingManagement_Thermostat_Mode) { ga="thermostatMode"}
Number  FF_Bedroom_Heater_Temperature  (gFF_Bedroom_Heater, gSensor_Temperature, gHeatingManagement_Thermostat_DefaultTemperature) { ga="thermostatTemperatureSetpoint" }
Number  FF_Bedroom_Sensor_Temperature  (gFF_Bedroom_Heater, gSensor_Temperature) { ga="thermostatTemperatureAmbient" }
Number  FF_Bedroom_Sensor_Humidity     (gFF_Bedroom_Heater, gFF_Bedroom, gSensor_Humidity) { ga="thermostatHumidityAmbient" }
````

**Comment by kpanchen** [comment]
I don't think mapping works at all. I've developed my own binding for my thermostat (Lennox iComfort) and it does use specific commands. So if I omit any mapping Google will show standard items and try to pass them to my binding which in turn binding won't recognize. If I add mapping google won't recognize it and just keep in Other mode (or if mapping is on one item only that item will be removed from the list).

**Comment by michikrug** [comment]
I am not sure if the mapping changes have already been deployed. :/

**Comment by kpanchen** [comment]
Possibly, I've try to analyze your current code and it seems fine to me (however I'm not that good with JS).
Thank you for your response!

**Comment by janwo** [comment]
@michikrug how can we find out? :)

**Comment by michikrug** [comment]
Should be working now
