### ISSUE TITLE
Google Assistant metadata keywords may be wrong

### ISSUE THREAD

**Issue by GijsTimmers** [openhab/openhab-google-assistant#154]
I just tried settting up my Tasmota switches as Google Assistant-controlled items with the metadata as described here:

https://www.openhab.org/docs/ecosystem/google-assistant/

My coffee maker switch did not get properly recognised when labeling it as `ga="CoffeeMaker"`. It would just not appear.

I resolved this by changing it to `ga="Coffee_Maker"`, following https://developers.google.com/assistant/smarthome/guides.

We should probably advice users to follow the labels listed on this website.

**Comment by michikrug** [comment]
Thanks for the info. We will have to update the documentation.

**Comment by michikrug** [comment]
PR created https://github.com/openhab/openhab-google-assistant/pull/159
