### ISSUE TITLE
Thermostat auto mode mapping not working

### ISSUE THREAD

**Issue by catsoo** [openhab/openhab-google-assistant#161]
I've got the following setup (**eco, cool** are just for testing):

`Group gWz_Thermostat  "Thermostat Wohnzimmer"   {ga="Thermostat" [ modes="heat=1,auto=0,eco,cool" ]}`

Behaviour:

1. Google Home does not display auto as a choice (only: heat, eco, cool)
2. If Thermostat is in auto mode (0), Google Home shows **other state** and disables all controls

Can't see an obvious problem in the JS code, it seems that auto is also not present in Google Home using the default config (which includes auto too)

**Comment by michikrug** [comment]
I think this is only an issue on Google's site.

Disabling controls could still be reasonable...
auto: "If the device supports an "automatic" mode where the temperature is set based on a schedule, learned behavior, AI, or some other related mechanism."

**Comment by catsoo** [comment]
Disabling makes sense I agree. The issue is that the state cannot be altered because _auto_ does not really seem to get registered at all. Below config (which ich what my Thermostat supports)

`Group gWz_Thermostat  "Thermostat Wohnzimmer"   {ga="Thermostat" [ modes="heat=1,auto=0" ]}`

Yields the below control view in Home - tapping on _Head mode_ does not offer to change the mode to auto (its greyed out too because of that, its only a label).

![WhatsApp Image 2020-05-10 at 20 54 55](https://user-images.githubusercontent.com/56756623/81507880-95c1a380-9300-11ea-98ec-74d800c729b3.jpeg)

**Comment by catsoo** [comment]
Closing this - confirmed that this is a Google Assistent issue / design choice. Auto Mode cannot be set through the user interface, but can be set using voice commands. Just validated with my Homematik devices, not sure why they thing this makes sense ;) Maybe worthwhile to add to the binding docs
