### ISSUE TITLE
Temperature sensor documentation 

### ISSUE THREAD

**Issue by kennetn** [openhab/openhab-google-assistant#162]
I was trying to setup a temperature sensor with GA and struggled a bit because it says that there are three items that are mandatory under the Thermostats. 
I eventually found that these are not really mandatory for a temperature sensor so I find this misguiding.
Maybe it is just me, but I would suggest to add a section called temperature sensors to the documentation with the same short explanation that we can use a google Thermostats to get the temperature into the google assistant.
The first two lines from the Thermostats are the same but there are only 1 mandatory item in the group.

**Comment by michikrug** [comment]
There is a sentence: "You can also set up a Thermostat for using it as a temperature sensor. To do so, create a Thermostat group and only add one item member as "thermostatTemperatureAmbient"."

Is this enough or do we need to extend that?

**Comment by kennetn** [comment]
Well I am not sure what the best solution is.
I did read the bottom part initially but I just figured that if the items were mandatory I had to write them. So it was the mandatory part that got me confused because it only really applies when used as a termostat.

**Comment by anordvall** [comment]
I have 30 temp sensors, and I'm not very happy with adding 30 groups for this :(
I tried with one, but when I ask about the temperature it says (translated to english) "Poolwater is inactivated and is currently 30 degrees". How to get rid of "is inactivated"?

Will there be a better solution for temperature sensors later on?

Many thanks for you help :)

**Comment by kennetn** [comment]
In my opinion the original issue with misguiding documentation is resolved so I will close this issue.
@anordvall I think you feature request / issue sounds more like it belongs on a forum.
