### ISSUE TITLE
Debugging long execution time for simple requests

### ISSUE THREAD

**Issue by cholawo** [openhab/openhab-google-assistant#164]
Hi, apologies if a github issue is not the right place to put this—feel free to remove.
I have been using this with my own openhab cloud server for over a year and it's been working great.
However in the last couple of months I've noticed that there is an increasing delay between my speaking to google and the command being performed.
If I give more voice commands right after a slow response for the same item, the response time is way quicker.   It's as if the item was sleeping somehow?
Attached is the firebase log where I switched an item 3 times.   You can see the first time at the bottom it took almost 2 seconds and was much quicker the next 2 times.

I don't notice any latency switching devices directly in openhab in the browser, either locally and on my cloud server.

Any ideas on how I can debug this further?

More info about my setup:
Openhab 2.5.5 on a raspberry pi 4 on ssd.   Openhab cloud running on a digital ocean server.   Most of the items I'd be switching are sonoff devices flashed with espurna, using mqtt 2.5.5 binding.   Firebase is deployed to europe-west2 (I'm in the UK).

![Screenshot 2020-06-04 at 09 59 45](https://user-images.githubusercontent.com/6299168/83738986-e8b32000-a64c-11ea-8bad-102bfa8dac46.png)

**Comment by michikrug** [comment]
Hi,
interesting issue.

From my perspective, I would not see an issue on the side of the google assistant function.
My feeling is that either the communication from the function to your openhab cloud instance is slow sometimes or the communication from your cloud instance to your openhab installation.
But if I read it correctly, you already tested the openhab cloud -> local part and did not see any delays - correct?

Cloud functions do "sleep" as they are only invoked when the endpoint is called. But nevertheless this should not result in such a delay (should! not proofed). This is why I suspect the cause rather in the communication between the components.

To debug this further I would suggest to test the two communication ways first.
1) openhab cloud to local openhab by sending some commands using the API for example
2) cloud function to openhab cloud by e.g. adding some timing logs to the output to see if the actual request to OH cloud takes long or there are other reasons

**Comment by michikrug** [comment]
I for my self have the function and openhab cloud both running on the same machine and do not see such issues as the function is also not "sleeping".

Since you already have a server you may also think about just hosting the function also there.

**Comment by cholawo** [comment]
Thanks for your responses they're really helpful.   
I've got the function running on my openhab server instead of firebase.  I used testServer.js and opened up a port for it.  Is that fine to do or is it insecure in some way?   It's got a bearer token going through it so it feels safe enough to me.   
It looks like the latency has gone away so I expect that it was some combination of firebase starting up, or the connection between that and my openhab cloud server.
I'm very pleased to have done away with that whole extra step of code going through firebase so thanks for the tip there!

**Comment by michikrug** [comment]
Really glad that I could help you.

This is more or less what I also do... using the testServer.
But I did not open an extra port but use a reverse proxy setting in apache (or nginx). Should not make any difference.
The good thing is that you can also talk via localhost to the openhab cloud instance.
