### ISSUE TITLE
Synonyms metadata not retrieved?

### ISSUE THREAD

**Issue by rmichalak** [openhab/openhab-google-assistant#167]
I was trying to add synonyms to my openhab items, without any luck.
After digging through the code I noticed this change: #120 - that introduced synonyms in metadata.

But... It seems that `synonyms` metadata is not requested here https://github.com/openhab/openhab-google-assistant/blob/master/functions/apihandler.js#L36

Am I missing something here or is this a bug?

**Comment by rmichalak** [comment]
Ok, so I hacked my cloud connector to return synonyms as well, verified that synonyms are returned when accessing https://myopenhab.org/rest/items/itemName?metadata=ga
 but still can't use synonyms in voice commands. 
Should those synonyms (if properly fetched) be visible in anywhere in Google Home app?

**Comment by michikrug** [comment]
You are very right, that we missed fetching those.
I already added the fix in another upcoming PR.

Although, I have to say that I not tested the synonyms so far with the Google Assistant.

**Comment by rmichalak** [comment]
I can try to test it, but not yet skilled in all that Google Cloud stuff. I tried to follow your tutorial, but I don't have my own Openhab Cloud and I'm not sure if it is possible to prepare dev environment without it (e.g. OAuth and `Setup your Database` steps are not possible (?) with myopenhab.org).

**Comment by michikrug** [comment]
You will need it to test the complete integration.
I run my own setup und will also do some tests with the synonyms.

**Comment by michikrug** [comment]
Just tested it, works fine :)

**Comment by rmichalak** [comment]
Great. When do you expect this to be merged and available by the official channel?

**Comment by michikrug** [comment]
Issue fixed
