### ISSUE TITLE
Thermostat not going below 10 degrees C

### ISSUE THREAD

**Issue by petterkatt** [openhab/openhab-google-assistant#179]
I have a outdoor temp sensor set up as a Thermostat, however since some time it does not show temperatures below 10 degrees.
Its currently -4.5 degrees outside, it shows up correct in Openhab cloud, but Google Assistant show it as +10.

Ive tried the [ thermostatTemperatureRange="-40,40" ] on the group without success.

The item is set up like this:
```
Group g_Ute_temp         "Ute Temp"        {ga="Thermostat"[ thermostatTemperatureRange="-40,40" ]}
Number Ute_temp          "Utetemperatur" (g_Ute_temp)   {channel="mqtt:topic:MyMQTTBroker:sonoff_carport:Temperature",ga="thermostatTemperatureAmbient"}
```

**Comment by michikrug** [comment]
Seems to be a known issue at Google's side.

Can you check if voice queries report the correct value?

https://issuetracker.google.com/issues/154169625

**Comment by petterkatt** [comment]
Tested now, and voice query reports the correct temperature.
Yestorday it didnt respond at all. Dunno if that was temporary or the fact that I didnt have any thermostatTemperatureRange configured.

Since this is confirmed as a Google issue and not a OpenHab issue, I guess this thread can be closed.
