### ISSUE TITLE
WaterHeater can't be controlled

### ISSUE THREAD

**Issue by candiesdoodle** [openhab/openhab-google-assistant#180]
hi

Here is my item definition:

        {
          "link": "http://192.168.1.XXX:8080/rest/items/VGeyser",
          "state": "OFF",
          "stateDescription": {
            "pattern": "%s",
            "readOnly": false,
            "options": []
          },
          "metadata": {
            "ga": {
              "value": "WaterHeater",
              "config": {
                "name": "VGeyser"
              }
            }
          },
          "editable": true,
          "type": "Switch",
          "name": "VGeyser",
          "label": "VGeyser",
          "category": "heating",
          "tags": [
            "Control"
          ],
          "groupNames": []
        }

On google assistant side, the item is discovered but can't be controlled. it also appears with a gear icon. Not sure whats wrong, but looks like OH might not be exposing the OnOff device commands (action.devices.commands.OnOff) properly with extended classes? just a hunch 
<img src="https://user-images.githubusercontent.com/20420013/102381701-8ec5e680-3fef-11eb-9b56-99a29c6a4b1e.jpg" width="30%">
![Screenshot_20201216-223228554_1](https://user-images.githubusercontent.com/20420013/102381711-908faa00-3fef-11eb-8246-01e174908cb4.jpg)

**Comment by michikrug** [comment]
A lot of devices do not have a user interface to control them in the Google home app.

This has nothing to do with the openhab integration but is probably a "work in progress" at Google's side.

You still can control them using voice commands.

**Comment by candiesdoodle** [comment]
Hi @michikrug 
thanks for replying. Yes, i am able to control this by voice. However, i noticed something interesting. The screenshots in the above post are when I expose a switch item with the tag `ga=WaterHeater`. However if i change it to `ga=Switch`, google home actually shows the device as a on/off water heater type of device. Though this stays only for a while. I replicated this with a totally new item. 

1. initial item definition

`Switch testitem "Test" {ga="WaterHeater"}`

As expected, google home shows as below upon refresh
<kbd><img src="https://user-images.githubusercontent.com/20420013/102479731-48bb6200-4085-11eb-87df-976be7b3c319.jpg" width="250px" ></kbd> <kbd><img src="https://user-images.githubusercontent.com/20420013/102479726-46f19e80-4085-11eb-9bc6-de4cbe2b4a55.jpg" width="250px" ></kbd>

2. Changed to switch

`Switch testitem "Test" {ga="Switch"}`

Refreshing google home, shows the updated item with ability to control and the device details show `Water Heater (Switch)`. It stays for a while so had to grab the screenshot while it was refreshing.

<kbd><img src="https://user-images.githubusercontent.com/20420013/102480280-0c3c3600-4086-11eb-8e35-b9a05556c7b5.jpg" width="250px"></kbd><kbd><img src="https://user-images.githubusercontent.com/20420013/102480283-0e05f980-4086-11eb-86f7-83d9591c18ee.jpg" width="250px"></kbd>
 
i dont know if this is any worth, so please feel free to close the issue if this is not relevant. many thanks!

**Comment by michikrug** [comment]
Interesting. Never saw this. Will also have a test.

But from my current understanding we can't do anything for now but maybe raising feature requests to Google to provide proper UI controls.

To be able to control it in the home app you will for now have to use a switch device type.

**Comment by SeveranExp** [comment]
I can confirm this behavior with a security system item. It's a basic switch, called "alarm". If set up as a switch I can toggle it on and off as a normal switch should. if I set it up as a security system I lose the manual toggle (but get the pincode entry).

**Comment by michikrug** [comment]
As this is an issue with Google`s implementation of the Google Home app we can not do anything about this here and I will close this issue.
