### ISSUE TITLE
Channel of type Player

### ISSUE THREAD

**Issue by peepshow-21** [openhab/openhab-google-assistant#181]
Hi,

Is there a way to map this type of channel in GA;
![image](https://user-images.githubusercontent.com/42150988/103158162-cb919a80-47b2-11eb-8c40-ae1df6de1aba.png)

I found it in Alexa as;
```
alexa="PlaybackController.playback"
```

Can't see it in GA plugin?

**Comment by michikrug** [comment]
Not yet in the public version, but I have implemented the device type `TV` in #175

You can see an example of the usage as Group with the possible members here: https://github.com/openhab/openhab-google-assistant/pull/175/files#diff-84782dc3ee3895fca917243e4d97119da1619c798d7d5e50db0b84a83c57e8fcR407

**Comment by peepshow-21** [comment]
If you get to the point where you wish me to test anything, I'm more than happy to do that.

**Comment by michikrug** [comment]
All the stuff is already testable. But you will need to setup your own openhab cloud instance and Google action to do so. (If you are not already running one.)
There you could checkout my not yet released code and test. 😁

**Comment by peepshow-21** [comment]
I currently run by OH on my own Linux local server. Could I run another local copy test there?

**Comment by michikrug** [comment]
`TV` device type has been implemented but not yet released. Will keep this open for feedback.

**Comment by michikrug** [comment]
Should be available. Please test :)
