### ISSUE TITLE
Google Assistant reacts on all Tags, not only on Metatags

### ISSUE THREAD

**Issue by Tobster77** [openhab/openhab-google-assistant#183]
I took a OH3 final release candidate installation and added my Tradfri bridge. Then I added some lights as equipment in my model and found the following unexpected behaviour:

Google Assistant seems to react upon the tags of a point, not only the metatags! When you have a non-semantic tag such as “Lighting” that is added automatically by some bindings such as Tradfri, Google Assistant will detect it and automatically add the point.

I expect that this would only happen with the dedicated metatags for Google Assistant, but whether I am not getting it, or the tag system is buggy at that point.

The issue can be resolved by manually removing the "lighting" non-semantic tag.

I opened a discussion here https://community.openhab.org/t/oh3-mainui-how-to-register-and-exclude-items-for-google-assistant-and-amazon-alexa/111107/7 in case it's my fault.

I initiated the bug report [here ](https://github.com/openhab/openhab-core/issues/2015) but I was told by @kaikreuzer to move the request here.

Thanks for help!

**Comment by michikrug** [comment]
As also stated in https://github.com/openhab/openhab-google-assistant/pull/175#issuecomment-753328566, I am totally up for removing all the support for configuration via tags in this integration.

The current mixture of tags and metadata is very confusing and intransparent.

**Comment by scatterthought** [comment]
Would it be possible to enforce this change only for OH3, while leaving tags in OH2? I think that would be helpful to avoid breaking the installations of existing OH2 users who aren't actively developing their systems. If someone's moving to OH3, I think it's reasonable to discontinue tag support.

I imagine this would require OH3 to somehow report its version to the cloud connector.

**Comment by jsetton** [comment]
I think it's fair to remove tag support since it was done in the homekit binding for OH3 (https://github.com/openhab/openhab-addons/pull/9277).

I am planning to do so with the Alexa skill but I like the idea to keep the support for OH2. It is actually easy to determine the the OH server version via the [REST API root resource](https://github.com/openhab/openhab-alexa/blob/master/lambda/smarthome/lib/rest.js#L139) endpoint.

**Comment by michikrug** [comment]
Fixed with https://github.com/openhab/openhab-google-assistant/releases/tag/v3.1.0
