### ISSUE TITLE
Security Systems and "exceptions"

### ISSUE THREAD

**Issue by SeveranExp** [openhab/openhab-google-assistant#186]
Hey everyone, I'm not sure if what I describe below is already implemented. Regardless, I'm leaving a request below :)
I checked all of the 22 open issues and none seemed to fit the bill. I come from this post:
https://community.openhab.org/t/google-home-and-security-systems-setting-up-exceptions/113200

As a user, I would like to be able to define Openhab sensors as "exceptions" for the security system, as detailed in the following page:
https://developers.google.com/assistant/smarthome/guides/securitysystem
(**Report arming exceptions** : When attempting to arm or disarm the system, you can provide additional context via exceptions codes that you report through the StatusReport trait.)

User story would go as follows:
A security system (Switch) controls access to a front door and back door. Back door is open. User tries to arm the alarm, google answers: "The back door is open."

More details:
* Should be possible to define if the sensor is a door or window for google to be able to inform what kind of device is open.
* Should be possible to define each sensor as blocking or non-blocking (if possible by default make it *blocking*. (to prevent user from arming the alam if the back door is open - security by default)
* Nice to have at this point: Zone Layers / Levels. Front Door and back door are SL1. Home Lab is SL2. Bedroom is SL3. This will allow google home to recognize different levels, and allow users to arm / disarm different areas easily. This can also be done by setting up multiple security systems, that’s why I consider it a nice to have.

**Comment by duanemck** [comment]
This sounds like what I was going for in my comment on #146.  I had added the concept of arm levels as well as the blocking/non-blocking and exceptions reported. As mentioned on the other thread, I'll make an effort this weekend to get my initial code rebased on the latest develop branch.

**Comment by SeveranExp** [comment]
@duanemck great! I just reread my original post and found a bunch of typos. I’ve corrected them. 
How are users informed about updates btw?
Or rather, how will I know when the updates are implemented? Do we get a notification or similar?

**Comment by duanemck** [comment]
I'm also quite new to this project, so I'm not sure how that works. In some cases this needs to be released along with a changes in OpenHab itself so I'm guessing it would need to be coordinated. Perhaps @michikrug can give some insight into the release/notification process?

**Comment by michikrug** [comment]
@SeveranExp Currently there is not a way that users are informed about new updates. The whole process is completely manual with no dedicated communication channel provided. From time to time the openHAB community board was used for spreading some news.

I do have planned to change that and use GitHub releases for that.
If my plans work out and we finish the implementation, you should always be able to see the time and content of the latest release here in the "Releases" section.

This project is completely detached from openHAB itself and does not rely on any updates or releases there.

**Comment by SeveranExp** [comment]
@michikrug hmm I see. 
having the GitHub releases would be great because then I could just follow the RSS feed and it would be easily shared.
Want me to open a feature request for it? :)

**Comment by michikrug** [comment]
@SeveranExp no need for a feature request, it's already WIP: https://github.com/openhab/openhab-google-assistant/pull/193

And that page showed on openhab that you linked is actually used from this repository: https://github.com/openhab/openhab-google-assistant/blob/main/docs/USAGE.md

This is also already reworked in https://github.com/openhab/openhab-google-assistant/pull/196

Maybe it is a good idea to add a version info and link to GitHub...

**Comment by SeveranExp** [comment]
@michikrug indees. Otherwise it becomes pretty hard for users to know what is currently available or if the information is outdated or not.

**Comment by duanemck** [comment]
> @SeveranExp Currently there is not a way that users are informed about new updates. The whole process is completely manual with no dedicated communication channel provided. From time to time the openHAB community board was used for spreading some news.
> 
> I do have planned to change that and use GitHub releases for that.
> If my plans work out and we finish the implementation, you should always be able to see the time and content of the latest release here in the "Releases" section.
> 
> This project is completely detached from openHAB itself and does not rely on any updates or releases there.

With regards to being completely detached, how do you handle the case where a change here results in changes to the metadat config screens in Openhab?

**Comment by michikrug** [comment]
> > @SeveranExp Currently there is not a way that users are informed about new updates. The whole process is completely manual with no dedicated communication channel provided. From time to time the openHAB community board was used for spreading some news.
> > I do have planned to change that and use GitHub releases for that.
> > If my plans work out and we finish the implementation, you should always be able to see the time and content of the latest release here in the "Releases" section.
> > This project is completely detached from openHAB itself and does not rely on any updates or releases there.
> 
> With regards to being completely detached, how do you handle the case where a change here results in changes to the metadat config screens in Openhab?

Currently, this is an unresolved dependency and would require a PR at the openHAB core components that contain those definitions. I started some discussion around that in #196

**Comment by duanemck** [comment]
We can probably close this now that #226 has been merged?
