### ISSUE TITLE
Fan attribute is "speed" in code it is "speeds"

### ISSUE THREAD

**Issue by mwinters-stuff** [openhab/openhab-google-assistant#187]
Noticed that the fan speeds do not work, setup own instance and debugged it.

The fan device attribute is sent into getAttributes as "speed" but that method is expecting "speeds".
A simple rename, and the fan speeds start to work.

Pull Request 175 may fix this already.

**Comment by michikrug** [comment]
Thanks for reporting. I'll recheck.

**Comment by michikrug** [comment]
As I did not find any usage of "speed" I consider this as resolved.
