### ISSUE TITLE
Thermostat Functionality

### ISSUE THREAD

**Issue by skimdankish** [openhab/openhab-google-assistant#19]
@marziman 

I believe I have the Thermostat functionality working (only with heat though...)  However, I am not an avid git user and little more than amateur-level at coding.  I am quite persistent when something doesn't work the way I like - it appears that google doesn't tell you that first there is a query to check the pre-req data is there, this wasn't possible until the most recent fork for Async Item States.

Traits:
https://developers.google.com/actions/smarthome/traits/temperaturesetting

DeviceTypes:
https://developers.google.com/actions/smarthome/guides/thermostat

Someone should definitely look it over before merging.  In order to share, need to understand how to 'push' correctly.

Remaining Issues:
   - Modes other than heating (I don't have the equipment to test), much of this was my error so might be able to be normalized back to original code
   - Celsius: I use F, by all accounts it should work (there was one function isEventFahrenheit, which was not working so I circumvented with a different check - looks like Alexa Skill)
   - Polling multiple: When you ask "What is the inside temperature?" You just get a bunch of numbers thrown at you.  Each item needs a Mode in string, current temp and setpoint need to have no more than 1 decimal point, otherwise it is discarded.  Perhaps there is a way to refine this in the code...?
   - Method for filling the response JSON is a bit...archaic, perhaps someone with greater skill than I would be able to find a more efficient way to extract the correct values (my method requires the data to be in a certain way in the *.items folder in OpenHAB)

thx,
Ryan

**Comment by marziman** [comment]
Done with https://github.com/openhab/openhab-google-assistant/pull/26
