### ISSUE TITLE
Setting up a speaker

### ISSUE THREAD

**Issue by woter1832** [openhab/openhab-google-assistant#192]
Hi,

In OH3, I have managed to configure a speaker with Mute (`ga=switch`), however the speaker device (`ga=Speaker`) is not giving me a volume control. In the GA app, under the room I get a speaker icon with a gear wheel. Tapping it just takes me to the settings with no volume control.

I've had a look at your code and Google's documentation and I can't see anything wrong, but this is all very new to me.

If I change the device to `ga=Light`, I get a dimmable "light" that controls the volume.

I am using the UI for configuration, but I did create the item in a `.items` file, which has the same effect:
```
Dimmer HEOS32Player1_Volume2 "Volume" <soundvolume> (LivingRoom) ["Point"] { synonyms="living room speaker", ga="Speaker" [ roomHint="Living Room" ] }
```

Have I missed some configuration or is there something wrong somewhere else?

T.I.A

**Comment by SEQUOiA87** [comment]
In general, Google Home' UI controls often only give you a subset of the controls defined by the traits offered by your device (see e.g. https://developers.google.com/assistant/smarthome/guides/speaker), but you can mostly "talk" to all offered traits. Means: If you are giving a voice command to your Assistant (or type the command as text into the text input of the Assistant on Android, for example) like "set volume of <speaker name> to 50 percent", you should get the expected result.

If not, I would suggest OH3 is missing something in the way it declares the speaker device.

@others: Please correct me if I'm wrong. Thanks!

**Comment by michikrug** [comment]
As already explained, there are still a lot of limitations with the control interface of the Google Home app. Nevertheless, voice commands should work fine. There is nothing we can do here. Please reach out to Google to get those controls ;)
