### ISSUE TITLE
AppSelector trait for TV

### ISSUE THREAD

**Issue by andiwirs** [openhab/openhab-google-assistant#199]
As [requested ](https://community.openhab.org/t/setting-up-a-tv-with-google-assistant-integration/118869/8?u=andirs)in the forum:

The Smart Home Television Guide also shows a trait “AppSelector” for starting apps like Netflix or Youtube.
It would be nice to have this available in Openhab as well

**Comment by michikrug** [comment]
Hey, what item type you would like to connect here?

Maybe you can construct an example scenario with openHAB items how this trait would work for you.

Thanks.

**Comment by andiwirs** [comment]
Hey thanks for taking the time to consider adding this feature. My setup works as follows:
On my TV i have Tasker running, which is waiting for HTTP Requests to start apps. For that I have defined a String item which triggers a rule that handles some tasks for preparation, like setting a default source, volume etc. and the http request of course.

```
Item
String	St_MultimediaPreset_Lr	"Multimedia Preset [%s]"	(gPersist_MapDB_Restore)
```

```
Sitemap
Selection item=St_MultimediaPreset_Lr mappings=["Off"="Off", "Startseite"="Startseite", "TV"="TV", "ARD Mediathek"="ARD Mediathek", "ZDFmediathek"="ZDFmediathek", "YouTube"="YouTube", "Netflix"="Netflix", "Kodi"="Kodi", "ARTE"="ARTE", "Steamlink"="Steamlink", "Chromecast built-in"="Chromecast built-in"]
```

So it would be perfect (for my setup) if i was able to set that String Item "St_MultimediaPreset_Lr" to one of the predefined values via Google Assistant :)

**Comment by Legion2** [comment]
I think this is related to #178

**Comment by michikrug** [comment]
Please have a look at #201

**Comment by andiwirs** [comment]
Thanks for merging #201 
Cannot wait for it to be deployed :)
