### ISSUE TITLE
Cannot connect via myopenhab.org

### ISSUE THREAD

**Issue by koenekle** [openhab/openhab-google-assistant#205]
Two days ago i setup my OH3(openHAB 3.0.2 Release Build) the first time via google assistant, as only one room of items appeared, I tried reseting my google home app. Unfortunately I am no further able to add my openhab connection in the google assistant. 

I can select to allow the new OAUTH token, get a popover saying "Linking you Openhab Account" and will be back to main screen with no devices. 

I tried: 

- deleting cache & local data of my google home app
- setting up a new home
- removing the oauth tokens from my myopenhab.org account
- removing all "ga" metadata from my other items
- using the example from: https://www.openhab.org/docs/ecosystem/google-assistant/

Here is the result from the rest-api: 
```
{
  "link": "https://home.myopenhab.org:443/rest/items/TestLight",
  "state": "NULL",
  "metadata": {
    "ga": {
      "value": "Switch"
    }
  },
  "editable": false,
  "type": "Switch",
  "name": "TestLight",
  "label": "Test Light",
  "category": "light",
  "tags": [],
  "groupNames": []
}
```

I might not be the only one with this problem: https://community.openhab.org/t/google-assistant-wont-connect/120698/24

**Comment by michikrug** [comment]
So far I would say this is not related to this integration.

Would be still open for more details on reproducibility...

**Comment by chriswalker01** [comment]
I have the same problem. Everything appears to go well when I deploy the function and action. I get a message saying Google successfully linked with Openhab but then it goes back to the home screen and no devices are listed.

It works when I use myopenhab.org. I only run into this problem when using my own deployment.

I have had this working in the past, back in 2019, so I'm not sure why I can't get it working now.

One thing I'm not sure about is, when deploying the function, do I need to enabled unauthenticated invocations?

Are there any restrictions on what regions you can use? Back in 2019 I used Tokyo, but I'm trying to use Sydney this time.

**Comment by chriswalker01** [comment]
I can't find anything meaningful (I don't think) in the logs.
The function's logs just say, "Function execution took 796 ms, finished with status code: 200" when I link but nothing else.

Openhab Cloud logs just say, "2021-07-03 14:34:29:2929 info: openHAB-cloud: server.authorization oauth2 request for scope: google-assistant"

I can't find anything else in any of the logs.

**Comment by chriswalker01** [comment]
Good news. I've fixed my issue by using the actual release, not the latest commit.

**Comment by michikrug** [comment]
Thanks for letting us know. I will have a look if there might be an issue with the latest commits.
