### ISSUE TITLE
Support Color for SpecialColorLight

### ISSUE THREAD

**Issue by cromefire** [openhab/openhab-google-assistant#234]
Please support a color item in the grouped light (SpecialColorLight), so it's possible to build a light that supports different shades of white (warm to cold) and actual color (RGB/HSV).

Something like this would be great:
```
Group  lightGroup { ga="Light" [ useKelvin=true, colorTemperatureRange="2000,9000" ] }
Switch powerItem           (lightGroup) { ga="lightPower" }
Dimmer brightnessItem      (lightGroup) { ga="lightBrightness" }
Number colortempratureItem (lightGroup) { ga="lightColorTemperature" }
Color  colorItem           (lightGroup) { ga="lightColor" }
```

**Comment by cromefire** [comment]
Shortcomings of the current solution (just a color item) are:
- Not possible to distinguish between HSV and Color Temperature
- No way to switch on and off without loosing the current brightness level

**Comment by michikrug** [comment]
With #215 we already added a separate switch to deal with the first mentioned shortcoming. Unfortunately, it's not live yet.

**Comment by michikrug** [comment]
Aren't color and colorTemperature competing values then? I need to check how Google can actually handle such scenarios.

**Comment by cromefire** [comment]
Yeah I'm aware of that, but it's not applicable to colored lights / lights with both color and shades of white as it's implemented in SpecialColorLight, that's why I noted it. So it's basically only a missing color item for SpecialColorLight.

**Comment by cromefire** [comment]
> Aren't color and colorTemperature competing values then? I need to check how Google can actually handle such scenarios. 

It looks fine form the app (it hast 6 shades of white and then a bunch of colors) and also from the documentation I think, although I can't say for sure and I haven't look at the actual APIs there. If not this is of course not possible.

**Comment by cromefire** [comment]
![image](https://user-images.githubusercontent.com/26320625/125348458-8737a780-e35c-11eb-8f89-ba99b1c3860b.png)
This example seems to indicate support, although it could be meant as a "color temperature via RGB" implementation (but that would render the color temperature range useless, right?)

**Comment by cromefire** [comment]
According to the [action.devices.commands.ColorAbsolute](https://developers.google.com/assistant/smarthome/traits/colorsetting#action.devices.commands.colorabsolute) Documentation this should also work out just fine, there should only be minor changes to the handling of `ColorAbsolute` (also allowing `SpecialColorLight`, if it has a `Color` item) and the `SpecialColorLight` Device required.

**Comment by michikrug** [comment]
When querying the device what color value should be reported?
TemperatureK or the RGB color value?
How to decide?

Ref. https://developers.google.com/assistant/smarthome/traits/colorsetting#examples_1

**Comment by cromefire** [comment]
That's a tricky one, maybe always set the unselected one to `NULL`?

**Comment by michikrug** [comment]
What do you mean with "unselected one"?

**Comment by cromefire** [comment]
Well when you select a color in the assistant app, set the temperature item to `NULL`.

**Comment by michikrug** [comment]
How would your device react to that?

And I don't mind so much about setting values, but more about querying the current state.

**Comment by cromefire** [comment]
In my specific case I have use a rule to convert stuff anyway (it need items for all 5 channels). In general I'm not aware of an example "off the shelf device" that supports RGB-CCT, would probably be worth investing, I don't really have any alternative in mind right now though. Querying would basically be return temperature if that's not null, otherwise return the color.
