### ISSUE TITLE
Temperature Sensor not working

### ISSUE THREAD

**Issue by ballle98** [openhab/openhab-google-assistant#238]
Trying to use TemperatureSensor to track outside temperature but it is not appearing in the Google home app.  Not sure if it needs to be replaced by a TemperatureControl queryOnlyTemperatureControl=true

```
value: TemperatureSensor
config:
  useFahrenheit: true
```

**Comment by michikrug** [comment]
Thanks for the report. I will have a look and check it in my setup.

**Comment by michikrug** [comment]
Sorry for the late response. I just checked it in my setup and it is working fine.
Please be aware that a sensor does not have a nice UI in the Google Home app and can only be queried using voice commands.
