### ISSUE TITLE
[feature] Implement trait MediaState for TV

### ISSUE THREAD

**Issue by cromefire** [openhab/openhab-google-assistant#240]
I'm trying to integrate a `TV` Device (actually just kodi) with the google assistant. It works fine (so I guess #181 can be closed) but it only supports control by voice, probably because it can't actually see if something is playing at all.
The docs also state that `MediaState` should be implemented if possible: https://developers.google.com/assistant/smarthome/guides/tv#required-traits
`Modes` and `Toggles` would also be great although a different topic.

**Comment by michikrug** [comment]
See #309

**Comment by michikrug** [comment]
New release should be live
