### ISSUE TITLE
implement vacum

### ISSUE THREAD

**Issue by fab33** [openhab/openhab-google-assistant#25]
In google Home, it's possible to command vacum. It will be very cool to implement it. I think it's like a switch.

**Comment by skimdankish** [comment]
It looks like vacuum deviceType supports OnOff, StartStop, Modes, Toggles, and Dock. 

https://developers.google.com/actions/smarthome/guides/vacuum

Unfortunately, I don't have a vacuum to try this with.

**Comment by fab33** [comment]
I can try it if you want

**Comment by marziman** [comment]
done with https://github.com/openhab/openhab-google-assistant/pull/118
