### ISSUE TITLE
Distinction between Switchable & Lighting tags unclear

### ISSUE THREAD

**Issue by bkpsu** [openhab/openhab-google-assistant#27]
When attempting to explain the difference between Switchable and Lighting tags recently, I read in the documentation that "Switchable" tags allow percentage settings, similar to the Lighting tag. To me, this is redundant and counter-intuitive, as "Switchable" (stemming from the word "Switch") should pertain to items that are discrete, not analog. I.e. there can be multiple switch positions, but as soon as you start discussing percentage/position in terms of home automation, we enter the realm of dimmers and volume knobs. 

Perhaps a more intuitive solution would be to add a third tag: [ "Dimmable" ], which would allow analog settings, while the [ "Switchable" ] tag would only pertain to ON/OFF (or Selection type) items?

This would then be aligned to the items definition, where Switch is a discrete ON/OFF while Dimmer is analog.

**Comment by skimdankish** [comment]
Perhaps in the future, but both Alexa and Google Assistant use the HomeKit nomenclature for items and from what I have seen this is how it was coded.  Prior to adding here, it would likely need to be added to the Openhab HomeKit standard so that it's consistent.

https://docs.openhab.org/addons/ios/homekit/readme.html

**Comment by marziman** [comment]
That is something we are tackling and trying to solve. Here is some discussion about that:
https://github.com/eclipse/smarthome/pull/4390#issuecomment-381493542
BR Mehmet

**Comment by bkpsu** [comment]
@michikrug @marziman - closing issue, as #118 and the new Google actions implemented make it pretty clear there are different types of Switch actions, for different types of devices.
