### ISSUE TITLE
Linking Openhab with Google Home does not show any devices

### ISSUE THREAD

**Issue by mdopp** [openhab/openhab-google-assistant#3]
When I try to add "smart-home-devices" in the Android Google Home App, everything seams to work fine, but no devices are added.

Google Home: Newest version (Google Pixel 1)
![google-home-version](https://user-images.githubusercontent.com/6053858/31587106-e278d38c-b1db-11e7-853f-1d7cd03e8441.png)

MyOpenhab.org => two devices currently added (1 light, 1 shutter)
![myopenhab-devices](https://user-images.githubusercontent.com/6053858/31587107-e291f51a-b1db-11e7-8d94-2b24aad001ca.PNG)

![adding](https://user-images.githubusercontent.com/6053858/31587104-e245dcca-b1db-11e7-8920-0e579a885b54.png)

![allow-access-to-myopenhab](https://user-images.githubusercontent.com/6053858/31587105-e25f359e-b1db-11e7-8b0d-fdf2a058ed23.png)

![successfully-added-but-no-devices-shown](https://user-images.githubusercontent.com/6053858/31587108-e2ab2c6a-b1db-11e7-8d71-0f64ca1735af.png)

Definition of "Terrassenlicht" => "Dimmer", and _later_ also added "Switch"
![terrassenlicht-definition](https://user-images.githubusercontent.com/6053858/31587226-4d302b60-b1de-11e7-973e-677c4c636290.png)

**Comment by marziman** [comment]
Hi,
Did you add the Tags to the Items, according the howto? Like e.g. „Lightning“ or „Switchable“?

**Comment by mdopp** [comment]
Hi, and thanks for the quick help.
You were right with your guess that I have not marked them in the *.items file, mostly because I had no file like this until now. I have tried to create it now, but somehow it still does not work. Tomorrow I will take a closer look at the Openhab2 <> HomeKit documentation. 
I will send an update later tomorrow night.

Thanks!

**Comment by mdopp** [comment]
Ok, was to tired yesterday. Works like a charm. Though it would be much cooler if the dubble-configuration caused by homekit would not be nessesarry, and the google-assistent would grap its data direct from the openhab2/rest-interface. This would also avoid errors, and make it more stupid-proove.

**Comment by mdopp** [comment]
@marziman 
OK => I just realized, that homekit-integration is not nessesary at all. I guess it might shorten setup-time for others if this would be part of the howto.

Open in Habmin and there the Channel you want to link with the Google Home, set "Tag" to "Lighting" and the "Description" to the desired name, and thats it. Just one place to configure everything.
