### ISSUE TITLE
Request: EnergyStorage

### ISSUE THREAD

**Issue by cholawo** [openhab/openhab-google-assistant#300]
My wife forgot to plug in her car last night. I would like to add querying the car's battery so that google can tell me its battery level (and we can add that to our going-to-bed assistant routine). Ideally I'd also ask google if the car is "plugged in" but I don't see any traits to support that.
Looks like we could add the [charger](https://developers.google.com/assistant/smarthome/guides/charger) device type and the [energy storage](https://developers.google.com/assistant/smarthome/traits/energystorage) trait.   
Would it be much effort to add?

**Comment by michikrug** [comment]
Does not seem like a lot of effort. I will take this under consideration.

**Comment by michikrug** [comment]
I implemented the functionality.
The device does show up in Google Home, but no controls are available.
Starting / stopping charging works. Querying the charge status and the plugged in status works too.

But I have no idea how to query the battery level...

Do you may have any suggestions what spoken query to try?

**Comment by cholawo** [comment]
Wow thanks for getting it done so quickly!  I hadn't read the spec closely enough, thanks for covering all of the available features!
