### ISSUE TITLE
wrong "brighten" and "dim" commands interpretation

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-google-assistant#31]
If say "ok google brighten my Desk light" , openHAB will receive a command "14";
if I say "ok google dim my Desk light", openHAB will receive a command "0" (OFF)
no matter of the previous level. 
Not sure if this is an issue with GH, but "brighten" command should be translated to an INCREASE command, not a "14" command and "dim" command should be translated to an DECREASE command, not to a "0" or "OFF" command.

**Comment by skimdankish** [comment]
@mvalla I believe there may be two things at play here.  I believe that Google uses 15% increments for "generic" brighten and dim commands.  So in this particular case at 14, if you ask to dim it would turn off.  However, I do believe I had this issue at higher levels which I included in #26 which is still undergoing testing.  But, just in case, I would try testing at a higher brightness to see what the results are.

**Comment by mvalla** [comment]
done more testing: 

- Dimmer 'iDeskDimmer' [channel brightness] at 90 > "dim desk dimmer" > 'iDeskDimmer' received command 0 (very wrong!)
- Color 'iFloorLamp' [channel color] at 90 > "dim floor lamp" > 'iFloorLamp' received command 63 (??)

Something is broken in the translation of dim/brighten GH commands to OH commands

**Comment by skimdankish** [comment]
@mvalla I have no color lights so I cannot speak to this, but the dim/brighten will be fixed.  I am running on this dev version and it works great.  You just need to deal with the 15% increment that GH uses for generic commands.

I would bet the Color item needs the same makeover, but I did not include that as I cannot test :(

**Comment by ben12** [comment]
I'm using a version with my pull request #18 and it work great for my color light (change color, dim and brighten).

NOTE: I just saw that my pull request has been integrated in the #26 ?

**Comment by skimdankish** [comment]
@ben12 I believe so? it was hard to track, i tried to be consistent to match how others were writing.

**Comment by MichaelFink** [comment]
I think the reason why dim/brighten commands are not working is because this addon currently doesn't support querying the current brightness of a lamp. 
But according to the [API reference](https://developers.google.com/actions/smarthome/) this is a prerequisite for those actions.
This also totally makes sense. Google Home is working stateless. So if you say 'dim the lights' it first needs to figure out what the current brightness is.
Therefore the referenced [PR](https://github.com/openhab/openhab-google-assistant/pull/26) probably fixes the issue.

**Comment by mvalla** [comment]
Yes this makes totally sense. I would leave this issue open until I can test it in my environment thanks to the new release of assistance integration (opefully will be updated soon)

**Comment by skimdankish** [comment]
@mvalla Have you tried this with the latest merge?  It should at least resolve the regular brightening.

**Comment by mvalla** [comment]
Tested and both:
- `ok google brighten my Desk light`
- `ok google dim my Desk light`

now work.
Therefore I close this issue.

**Comment by marziman** [comment]
Closing this.
