### ISSUE TITLE
openHAB docs article

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-google-assistant#33]
Hello!
If I am not mistaken, an article on the Assistant integration should be added to the openHAB docs page here: https://docs.openhab.org/addons/io.html
Correct?

If so, the solution as I would imagine it is to create a separate markdown document for it, which doesn't include technical and developer content (in contrast to the main README).
Here are existing files that followed that idea:

* https://github.com/openhab/org.openhab.ui.habpanel/tree/master/doc
* https://github.com/openhab/openhab-mycroft/blob/master/USAGE.md
* https://github.com/openhab/openhab-alexa/blob/master/USAGE.md

Anyone out there willing to provide such a file?

**Comment by marziman** [comment]
DONE.
See:  https://github.com/openhab/openhab-google-assistant/blob/master/USAGE.md
