### ISSUE TITLE
Control Squeezebox player via Google Assistant 

### ISSUE THREAD

**Issue by tophee** [openhab/openhab-google-assistant#336]
I am trying to setup a Squeezebox Player to be controlled via Google Assistant and I have figured out that I need to classify it (the equipment-group) as "TV" in the `ga` metadata and then the volume item as tvvolume, the player as tvtransport, etc.

But I can't seem to get it to work. The only device that shows up on Google Assistant is the on/off button (power item). The fact that it has correctly inherited the name of the TV group tells me that GA is seeing the group and one of its members, but I don't understand why it doesn't see the other items/traits.

Is there perhaps some incompatibility with the Squeezebox Binding? But if that were the case, I'd expect the controls to show up, but the execution fail. I don't even get the controls.

I can control the player fine via the openHAB UI, but not from Google Assistant (except for turning it on and off).

Any idea what might be going wrong?

**Comment by michikrug** [comment]
As far as I know the Google Home UI only provides the on/off controls for TV devices. All the other traits are only available via voice commands. Can you verify this?


In general the Google Home app is unfortunately very limited in terms of controlling devices.

**Comment by michikrug** [comment]
Can you share you item configuration for validation?

**Comment by tophee** [comment]
> As far as I know the Google Home UI only provides the on/off controls for TV devices. All the other traits are only available via voice commands. Can you verify this?

Oh, that could explain things. But the reason I went for the Google Home UI while testing wast that the voice commands didn't work, so I thought I'd eliminate one possible point of failure... When I try to play something on the player via voice command (e.g. "play music on bathroom player", it tells me that I need to specify the device. Since Bathroom player is the device, I don't know what more to do.

I did my config via the GUI, so I have no text config to share. Here are some screenshots:

This is the player item (aka "TV group")
<img width="1422" alt="Microsoft Edge-2022-04-03 at 16 48 35@2x" src="https://user-images.githubusercontent.com/3662750/161437929-9e63b5b2-59c7-4886-82a7-d276a7501f05.png">

This is the controller (aka "tvtransport")

<img width="1421" alt="Microsoft Edge-2022-04-03 at 16 49 07@2x" src="https://user-images.githubusercontent.com/3662750/161437967-13b5fc45-bf14-4f94-ac60-fde8a6b9934c.png">

These don't work (on OpenHAB but not on Google assistant, i.e. they don't even show up)

What I have managed to get to work are switches. Whenever I turn something into a switch, it does show up on GA and it can be triggered through a voice command. For example:

<img width="1422" alt="Microsoft Edge-2022-04-03 at 16 49 26@2x" src="https://user-images.githubusercontent.com/3662750/161438035-a8f68e7a-00b7-4105-bd3f-7a311094c640.png">

This Play/Pause item is provided by the Squeezebox binding in addition to the controller item. in the GA metatag I gave it the custom name "Bathroom music" and the Voice command "Turn on bathroom music" does trigger the music on.

I'm glad du have found this workaround, but I'd still like to know whether I am doing something wrong, whether google home just doesn't work beyond on/off (but what's the point of the tvtransport trait then?) or whether there is an incompatibility between the squeezebox binding and GA.

**Comment by michikrug** [comment]
I have tested a similar setup with dummy items at my end.
There is no Google Home UI controls, but the device appears. When also defining a `tvPower` item, at least an On/Off button is available.

```
Player TvTransport "TV Transport" (TVGroup) { ga="tvTransport" }
Group TVGroup "Bildgeber" { ga="TV" }
```

![Bildschirmfoto 2022-04-04 um 11 49 48](https://user-images.githubusercontent.com/727517/161519372-2acfa0ae-be70-461e-9c7c-91e9ea4d25a9.png)

Voice control like "Start playback on Bildgeber" works as expected.

```
2022-04-04 11:37:38.374 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'TvTransport' received command PLAY
2022-04-04 11:37:38.381 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'TvTransport' changed from NULL to PLAY
```

**Comment by tophee** [comment]
Maybe I should try defining my items in item files to make sure I have the correct setup...  But I have also never used the "start playback". I would probably say "Play music on Bildgeber".  Does that work for you? Also, can you confirm that the `next` command also works (to skip to the next song). Because that's the one I've done most of my testing with.

**Comment by michikrug** [comment]
Can confirm `next` working.

`2022-04-04 14:44:17.549 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'TvTransport' received command NEXT`

"Play music" does not work as Google does not get the device.
I assume it wants to start Spotify and requires a streaming device to be stated, like a Chromecast.

**Comment by tophee** [comment]
OK, that is very useful to know. "Start playback" is not an acceptable command for my family (and even I struggle with that kind of language), so I'll just use my switch with "Turn on" instead. "Turn on Bathroom music" feels much more natural than "Start playback on bathroom player"...

But just to clarify: what exactly do you say when you test the next command? Is "OK, Google next" enough?

Might there be a difference between a situation where the playback was started by GA and where it was started from elsewhere? i.e. that it will understand the meaning of "OK, Google, next" based on the context when it previously started  the playback, but not if it didn't?

**Comment by michikrug** [comment]
I believe "Ok Google, next" only works for Nest / Assistant devices that are actually playing a track.
For different devices the context is missing.

I believe I said something like "next track on Bildgeber".

**Comment by tophee** [comment]
OK I see. I think part of my confusion then came from the fact that the player I am asking GA to playback from is the actual Nest device I am talking to. But GA doesn't know that because it is asking OpenHAB to ask Logitech Media Server to cast music to the Nest device. At first, I assumed that casting is a one-way operation in the sense that the receiving device can't tell the sending device to stop casting, but then that actually worked, i.e. I could tell the Nest device "OK Google, pause" and it worked, the server stopped casting. So I somehow assumed that also the other transport commands would work like that...
