### ISSUE TITLE
google-assistant - Valve and Sprinkler

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-google-assistant#338]
ga setup OK with lights, thermostats and switches, google home APP on iOS 

`Switch { ga="Valve" } `- showing but working only by voice assistant 
https://community.openhab.org/t/rollershutter-and-valve-are-working-with-google-home-mini-but-not-with-google-home-app/101099/3

Switch { ga="Sprinkler" } - showing in app but state is " Stopped" -> 'Not responding"  - the same working only by voice

## Expected Behavior
google home app is showing icon Valve or Sprinkler and touching it works like Lights  Switch = On/OFF

**Comment by michikrug** [comment]
Hello and sorry for the (very) long delay.

I have checked both types.

Sprinkler does have an UI in Google Home and works as expected.

![Screenshot_20221031-193802.jpg](https://user-images.githubusercontent.com/727517/199084565-d48598a2-5cf2-4ce9-a59a-40b35df728a5.jpg)

For the Valve type, Google Home does not provide any UI and this is a limitation by the app itself and has nothing to do with our integration.

![Screenshot_20221031-193807.jpg](https://user-images.githubusercontent.com/727517/199084683-13d19cf0-9411-44dd-b97e-6a1bc16d46ee.jpg)

Nevertheless, both will work with voice or text commands just fine.
