### ISSUE TITLE
Too many items exposed to Assistant

### ISSUE THREAD

**Issue by JohannesPtaszyk** [openhab/openhab-google-assistant#34]
Hey, 

I got following setup:

1 dimmer which includes 4 bulbs
1 dimmer which includes 3 bulbs
2 dimmers which include 1 bulb

I tagged the dimmers, so Assistant can see them and everything is working like charme, but the issue I have is, that the Google assistant seems to see more items which are named "brightness", but in my items file I do not have any more items than my dimmers setup.

**Comment by marziman** [comment]
Hi @JohannesPtaszyk 
thats sounds strange. Maybe you have tagged them with some other tags beside "Lightning"?
Can you explain which items you tagged and how?

Thanks & BR
Mehmet

**Comment by JohannesPtaszyk** [comment]
Yeah, I am wondering how that is happening aswell. 
I got no other items or tags in my file. But I could figure out, that the brightness items exposed to the home are some of the bulbs which are included in the dimmer items.

**Comment by JohannesPtaszyk** [comment]
This is my items file:

Dimmer Wandlampe_ColorTemperature "Wandlampe Color" {
			channel="tradfri:0220:gatewayOne:myColorTempBulb1:color_temperature",
			channel="tradfri:0220:gatewayOne:myColorTempBulb2:color_temperature",
			channel="tradfri:0220:gatewayOne:myColorTempBulb3:color_temperature",
			channel="tradfri:0220:gatewayOne:myColorTempBulb4:color_temperature" }
Dimmer Wandlampe_Brightness "Wandlampe Brightness"[ "Lighting" ]  { 
			channel="tradfri:0220:gatewayOne:myColorTempBulb1:brightness",
			channel="tradfri:0220:gatewayOne:myColorTempBulb2:brightness",
			channel="tradfri:0220:gatewayOne:myColorTempBulb3:brightness",
			channel="tradfri:0220:gatewayOne:myColorTempBulb4:brightness" }


Dimmer Deckenlampe_ColorTemperature "Deckenlampe Color" { 
			channel="tradfri:0220:gatewayOne:myColorTempBulb5:color_temperature",
			channel="tradfri:0220:gatewayOne:myColorTempBulb6:color_temperature",
			channel="tradfri:0220:gatewayOne:myColorTempBulb7:color_temperature" }
Dimmer Deckenlampe_Brightness "Deckenlampe Brightness" [ "Lighting" ] { 
			channel="tradfri:0220:gatewayOne:myColorTempBulb5:brightness",
			channel="tradfri:0220:gatewayOne:myColorTempBulb6:brightness",
			channel="tradfri:0220:gatewayOne:myColorTempBulb7:brightness" }


Dimmer Schreibtisch_ColorTemperature "Schreibtisch Color" { 
			channel="tradfri:0220:gatewayOne:myColorTempBulb8:color_temperature" }
Dimmer Schreibtisch_Brightness "Schreibtisch Brightness" [ "Lighting" ] { 
			channel="tradfri:0220:gatewayOne:myColorTempBulb8:brightness" }


Dimmer Nachttisch_ColorTemperature "Nachttisch Color" { 
			channel="tradfri:0220:gatewayOne:myColorTempBulb9:color_temperature" }
Dimmer Nachttisch_Brightness "Nachttisch Brightness" [ "Lighting" ] { 
			channel="tradfri:0220:gatewayOne:myColorTempBulb9:brightness" }

**Comment by skimdankish** [comment]
@JohannesPtaszyk 

I bet the Action is taking "Deckenlampe" and breaking each channel as it translates into Google's format. 
 As a workaround you can just have the item with tag setup and have Openhab handle brightness using a rule.

I'll test this out when I have a moment so see how the function is translating the items with multiple channels and handing over to Google as I don't have this setup right now.

In some cases where I have multiple lights I have also embraced the multiple items in GH so you say "Hey Google, set deckenlampe(n?) brightness to... (and it contextually changes them all, also not sure about plurality as mein Deutsche ist schlecht).

Perhaps this will help in the meanwhile??

**Comment by marziman** [comment]
I would close it. Feel free to re-open a new issue if you think that is still a problem.

Thx & BR
Mehmet
