### ISSUE TITLE
Camera in google home app not working

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-google-assistant#342]
i can stream it to chromcast device but not play it in the google home app (iOS). Camera working ok in openhab, direct urls etc. binding  IP camera - dauha 

https://developers.google.com/assistant/smarthome/traits/camerastream#action.devices.commands.getcamerastream

What cameras can be viewed in Google Home app?
You can tap on the camera icon in the home view of the Google Home app. Here, you'll see all existing Nest cameras, including Nest Doorbell (battery), Nest Cam (battery), Nest Cam with floodlight and Google Nest Cam (wired).Sep 3, 2021

**Comment by michikrug** [comment]
As far as I know, you can not view any streams in the Google Home app. Google only supports streaming to Chromecast and Nest devices.
