### ISSUE TITLE
is it working ? ga="TemperatureSensor"

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-google-assistant#344]
Not sure how to use 
   `Number PiotrekThermostatCurrentTemp 		"AktualnaTemperatura [%.1f C] Piotrek"                  (gPiotrek)	{homekit="TemperatureSensor", **ga="TemperatureSensor" [ useFahrenheit=false ]** ,channel="mqtt:topic:mymqttbroker:Temp_04:temperature"}`
	 
i can add this device but i dont see actually the temperature in the home app ? Should it use it ? need to put there temperature and humadity

**Comment by michikrug** [comment]
Unfortunately, Google does not provide a user interface for the sensors in the Home app so far. You can only query the state by voice (or typed) commands.
