### ISSUE TITLE
Multiple Synonyms not working

### ISSUE THREAD

**Issue by Owlbertz** [openhab/openhab-google-assistant#369]
Hi,

based on [this code](https://github.com/openhab/openhab-google-assistant/blob/6fc2ec5ec428faec6b42408c7042928e7d4244e4/functions/devices/default.js#L72) there should be no difference in the amount of synonyms.
However, this is working when using "Terrassenrollo"
```
Rollershutter Shutter_Terrace_Level_GA         "Rollo Terasse"       (Group_GoogleAssistant) { ga="Shutter", synonyms="Terrassenrollo" }
```
and this is not working with any of the synonyms:
```
Rollershutter Shutter_LivingRoom_Level_GA      "Rollo Wohnzimmer"    (Group_GoogleAssistant) { ga="Shutter", synonyms="Rollo im Wohnzimmer,das Rollo Wohnzimmer,das Rollo im Wohnzimmer" }
```
It seems that as soon as there are multiple synonyms stated, none is working.

**Comment by michikrug** [comment]
Sorry to tell you, but at least for me it works as expected - also with multiple synonyms.

An issue I could imagine is that you state room information in the names. Those will very likely be stripped when talking with the assistant as it will use that part for the actual room identification.
So if you ask "Schließe das Rollo im Wohnzimmer", Google will very likely only use "das Rollo" as the device name and will search in your rooms for "Wohnzimmer".
As Google Home works very well with rooms, I wonder why you added them in your names?!

**Comment by Owlbertz** [comment]
> As Google Home works very well with rooms, I wonder why you added them in your names?!

To be honest, I don't know. Guess I felt the need to distinguish them. How else would I perform the initial assignment to the rooms?

**Comment by michikrug** [comment]
> > As Google Home works very well with rooms, I wonder why you added them in your names?!
> 
> To be honest, I don't know. Guess I felt the need to distinguish them. How else would I perform the initial assignment to the rooms?

You can e.g. use the `roomHint` property. But you nevertheless have to assign a device to a room after you add it to Google Assistant / Home. So I don't really know how you did it so far...?! 

![Screenshot_20221031-140920~2.jpg](https://user-images.githubusercontent.com/727517/199015427-60068663-1908-4984-8397-8ff3895fe913.jpg)

**Comment by Owlbertz** [comment]
Yeah that's cool until I add 10 shutters and have to assign them. But I guess since I did that I should be able to rename them and get rid of the room inside the label.
