### ISSUE TITLE
Documentation Error for TV group

### ISSUE THREAD

**Issue by waynethomas69** [openhab/openhab-google-assistant#380]
The Openhab documentations give an example config for a TV group with an error. Currently reads:
`Group  tvGroup { ga="TV" [ volumeDefaultPercentage="20", levelStepSize="10", volumeMaxLevel="100", transportControlSupportedCommands="NEXT,PREVIOUS,PAUSE,RESUME", availableChannels="1=Channel1=NBC,2=Channel2=CBS", availableInputs="hdmi1=xbox:gaming,hdmi2=settopbox", availableApplications: "youtube=YouTube:Tube,netflix=Netflix:Chill" ] }`

but should read:
`Group  tvGroup { ga="TV" [ volumeDefaultPercentage="20", levelStepSize="10", volumeMaxLevel="100", transportControlSupportedCommands="NEXT,PREVIOUS,PAUSE,RESUME", availableChannels="1=Channel1=NBC,2=Channel2=CBS", availableInputs="hdmi1=xbox:gaming,hdmi2=settopbox", availableApplications="youtube=YouTube:Tube,netflix=Netflix:Chill" ] }`

The issue is the `:` after `availableApplications` should be `=`

**Comment by michikrug** [comment]
Thanks for letting us know :)

**Comment by michikrug** [comment]
Will be fixed in one of the next PRs.
