### ISSUE TITLE
New TV group in OH 3.3.0 only detecting power item in google home

### ISSUE THREAD

**Issue by waynethomas69** [openhab/openhab-google-assistant#381]
I have created multiple TV groups in openhab, both using text config and the openhab GUI, and in every case the only item that google assistant detects is the power (which does work). Mute, volume and input are not detected/offered in google (nor any of the others). Below is the text config take from the openhab documentation (and corrected).

`Group  tvGroup { ga="TV" [ checkState="true", volumeDefaultPercentage="20", levelStepSize="10", volumeMaxLevel="100", transportControlSupportedCommands="NEXT,PREVIOUS,PAUSE,RESUME", availableChannels="1=Channel1=NBC,2=Channel2=CBS", availableInputs="hdmi1=xbox:gaming,hdmi2=settopbox", availableApplications="youtube=YouTube:Tube,netflix=Netflix:Chill" ] }`
`Switch powerItem       (tvGroup) { ga="tvPower" }`
`Switch muteItem        (tvGroup) { ga="tvMute" }`
`Dimmer volumeItem      (tvGroup) { ga="tvVolume" }`
`String channelItem     (tvGroup) { ga="tvChannel" }`
`String inputItem       (tvGroup) { ga="tvInput" }`
`String applicationItem (tvGroup) { ga="tvApplication" }`
`Player transportItem   (tvGroup) { ga="tvTransport" }`

I have existing items (including two thermostat groups) that still work perfectly. I also created a new light group to check if it was an issue with new groups in general. There were some issues with the light group (will raise separate issues), but I was able to get a fully functional light group up and running eventually.
After creating, recreating, importing, re-importing, and waiting a week the TV groups still only detect the power item.

**Comment by waynethomas69** [comment]
I discovered by chance that google home does detect the various other controls (input, volume, mute, etc.) but only offers control by voice ("hey google, switch downstairs TV input to kodi"). The google home app only shows power. This behaviour is different from other group items such as thermostats and coloured lights, where the other types of control are also shown in the app.
This seems like it might be an issue with google home rather than the openhab interface, but I'm not certain.

**Comment by duanemck** [comment]
I'm not sure of the specifics for TVs but I have noticed this behaviour for other items like alarm systems. The touch interface seems to be quite limited compared to the voice interface and this is indeed a limitation of Google Home and not Openhab.

**Comment by michikrug** [comment]
I can only agree with what has already been written. The Google Home app offers only very limited control functionality for most device types. This is completely out of the scope and influence of the openHAB integration.
I have also never seen any type of documentation indicating what should and should not be available.

I understand that this is not a pleasant state and also checking configurations can become very tedious.
Still, you should be able to control everything by voice or text via Google Assistant.

**Comment by waynethomas69** [comment]
The only real issue was that I wrongly assumed the OpenHAB interface had not worked. It wasn't until someone in the family randomly said a command a few weeks later (which worked) that I realised OpenHAB was actually working perfectly!
Perhaps a note in the documentation just pointing out the limitations of the Google Home GUI?

**Comment by michikrug** [comment]
@michikrug TODO: add note about GUI limitations in the documentation
