### ISSUE TITLE
openHAB GUI does not offer all Light Group Attributes

### ISSUE THREAD

**Issue by waynethomas69** [openhab/openhab-google-assistant#382]
Currently the openHAB GUI only offers lightBrightness and lightColorTemperature as attributes for a light group. The lightColor and lightPower attributes are missing. Current work-around is to modify the attribute manually in the "Code" tab.

![image](https://user-images.githubusercontent.com/22013674/185815184-abecf1c6-94bf-4e83-8bdc-8357bd6b04e6.png)

**Comment by michikrug** [comment]
This is a known problem that is currently not easy to solve.
The attributes that are displayed to you in the openHAB GUI are maintained in a different place than this integration.
Therefore, you always have to update these configurations as soon as the integration has received new options.
In addition, publishing the changes is bound to openHAB releases.

This is why I can for now just ask you to use the openHAB Google Assistant Documentation and add the missing attributes using the code tab, like you described.

**Comment by rkoshak** [comment]
Where is that maintained? The webui's repo? Is an issue already opened for this? I also just recently helped someone with the problem that "Light" changed to "SpecialColorLight".

**Comment by michikrug** [comment]
Issue is tackled within https://github.com/openhab/openhab-webui/pull/1539

**Comment by michikrug** [comment]
Should be rolled out with the openHAB release 3.4.0
