### ISSUE TITLE
New Light group not detected unless colorTemperatureRange set

### ISSUE THREAD

**Issue by waynethomas69** [openhab/openhab-google-assistant#383]
After setting up a new light group in openHAB, google home did not detect the item. After modifying the group to include the optional colorTemperatureRange google home was then detected the item and everything works as expected.
Subsequently removing the colorTemperatureRange setting didn't affect the item - it is still in google and continues to work.

**Comment by michikrug** [comment]
Could you share your group and item configuration?

**Comment by waynethomas69** [comment]
Once it is detected it continues to work regardless of whether colorTemperatureRange is set or unset. I'll create a new dummy group/items and capture the progression shortly.

**Comment by waynethomas69** [comment]
Hi there, created a couple of new test items using the config file and the GUI, and didn't encounter the same issue. Everything works as it should - colorTemperatureRange was not required.
I must have made some other mistake previously.
