### ISSUE TITLE
Need to Relink Google Assitant to OpenHab for new items

### ISSUE THREAD

**Issue by digicos** [openhab/openhab-google-assistant#39]
I did a successful testing of turning on the lights ON/OFF (existing items before linking google assistant to OpenHab) using my google home mini and android assistant. I then added a new item. This new item did not get automatically updated in google assistant , HomeControl -> Devices..shouldn't any newly added item get auto updated there?.. Or am i missing some configuration..Please help.. Thanks!

**Comment by mdopp** [comment]
Nope. As far as i know, you have to say "sync devices" or remove openhab from your Assistent anderen re-add it again

**Comment by digicos** [comment]
Thanks @mdopp ..I'll try it out the "sync devices" and let you know..
Removing and adding OpenHab to assistant, synchronizes the devices information..

**Comment by alibahba** [comment]
Issue can be closed.

**Comment by marziman** [comment]
Closing...
