### ISSUE TITLE
Google Link only works when Switches defined in .Item 

### ISSUE THREAD

**Issue by Rar9** [openhab/openhab-google-assistant#4]
Google home only gets paired when Switches are manually added to .Items as configured via UI is not using:

Switch switch_name " Swich Name" <light> (your group) ["Lighting"] {channel="your id"}

**Comment by marziman** [comment]
Hello Iam not sure, but this is not related to the oh google assistant here. It is rather some general tagging restriction. I would not track tjis here

**Comment by marziman** [comment]
The way to add Tags is over the item files and this is known. So I wanna avoid to put issues here, which are not related to this implementation.

**Comment by mdopp** [comment]
@Rar9 I have it working without the *.item files (and without homekit binding). I use Habmin, and within the Channel that I want to use, I just set the "Tag" to "Lighting", and the description to the desired name.

**Comment by marziman** [comment]
Closing this, since this is not directly related to this implementation. Adding tags is done by the item files or by habmin. I am not sure why this have been added as issue?
