### ISSUE TITLE
Light groups not detected

### ISSUE THREAD

**Issue by waynethomas69** [openhab/openhab-google-assistant#407]
As a follow up to #383, the two light groups I had previously created (one in GUI, one in config files) are no longer detected by google home at all. I even tried setting the colorTemperatureRange again, but this did not influence it this time (it was probably a red-herring).
Here is the config file that isn't detected:

```
Group  lightGroup { ga="Light" [ useKelvin=true, colorTemperatureRange="2000,9000" ] }
Switch powerItem            (lightGroup) { ga="lightPower" }
Dimmer brightnessItem       (lightGroup) { ga="lightBrightness" }
Color  colorItem            (lightGroup) { ga="lightColor" }
Number colorTemperatureItem (lightGroup) { ga="lightColorTemperature" }
```
and here are some screenshots of the gui configured group that also isn't configured:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/22013674/200150765-d9c75c6e-e393-47b7-9021-d54c21e4b9f1.png">

<img width="740" alt="image" src="https://user-images.githubusercontent.com/22013674/200150771-0dbc6ac7-7abc-4469-93ab-1bb36ba0e1a3.png">

<img width="740" alt="image" src="https://user-images.githubusercontent.com/22013674/200150779-80dc7ab9-3943-46ba-9b30-a973903f648c.png">

<img width="740" alt="image" src="https://user-images.githubusercontent.com/22013674/200150781-5f6f90ff-b2c2-4002-9e08-4a44593ec924.png">

<img width="740" alt="image" src="https://user-images.githubusercontent.com/22013674/200150789-ced664ae-31e6-48be-a4fc-a17637dd6fdb.png">

**Comment by michikrug** [comment]
Thanks for the report. Will debug your example in my test setup.

**Comment by michikrug** [comment]
The first thing I already spotted is the incorrect use of `useKelvin` that is now called `colorUnit`

As of #337:

useKelvin=true is replaced by colorUnit="kelvin"

**Comment by waynethomas69** [comment]
When did that setting change?
Either way, changed the text-based config and still not detected. The GUI-based config did not have that option selected (so was previously blank); added it manually in the code tab for the ga metadata and still not detected either.
![image](https://user-images.githubusercontent.com/22013674/200390790-f8ed0257-c9e9-4efd-b79f-237a1d554a4c.png)

**Comment by michikrug** [comment]
It changed with https://github.com/openhab/openhab-google-assistant/releases/tag/v3.5.0

So 10 days ago.

It also explains the second error. Complex lights are now called "specialcolorlight".

**Comment by michikrug** [comment]
I also need to say that the options presented in the UI are not up to date with the latest changes here. This is a known issue we currently try to solve.

**Comment by waynethomas69** [comment]
specialcolorlight fixed it. I didn't think to look for breaking changes since I hadn't changed anything myself and didn't realise the cloud connector was updates completely independently.
Thanks for your help!
