### ISSUE TITLE
Support color temperature for lights

### ISSUE THREAD

**Issue by thedannymullen** [openhab/openhab-google-assistant#41]
Hello, it seems that when my hue or trad Fri lights are connected through the Kenyan only saying make the light warmer or cooler does not function.

They are in process of added this to the alex a features and i am wondering can it be added on the Google connector?

Thanks!

**Comment by michikrug** [comment]
"Color Temperature" is implemented and will be available as soon as the recent changes are deployed

**Comment by blockbasti** [comment]
@michikrug is there an ETA for when this new version will be deployed?

**Comment by michikrug** [comment]
@blockbasti unfortunately I can (for now) just always refer to @marziman 😞, as he is the only one who has access to the deployments...
