### ISSUE TITLE
Give an error or connect even if no items in myopenhab

### ISSUE THREAD

**Issue by thedannymullen** [openhab/openhab-google-assistant#42]
I found that unlike other services alexa, ifttt for example.  The Google connector will not connect if I have no items with a labe! in myopenhab.  In addition to not connectimg, it gives no error.  I am wondering if any fixes could be made so new users won't feel lost?  

ALso, I am not sure if this comes from the myopenhab  or the openha b install, but can it be made so if you don't label your items Google assumes the name of the item as the label?

Here is my exAmple : 
Items file with connection problem
 "Switch switch1  "Lighting"  channelinfo". <=== cause Google to have unknown error
 "Switch switch1 "switch1label"  "lighting" chanelinfo" <=== Google works.  

Can we make it so that if the label is empty we use the name?

**Comment by Skinah** [comment]
I also have this issue.

**Comment by michikrug** [comment]
- [ ] @michikrug add fallback to `item.name`

**Comment by michikrug** [comment]
Fixed with https://github.com/openhab/openhab-google-assistant/commit/28f5389761d6f7cb1976729cb5278ac46063bf72
