### ISSUE TITLE
TemperatureSensor does not work because it is missing required temperature range attributes

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-google-assistant#426]
According to https://developers.home.google.com/cloud-to-cloud/traits/temperaturecontrol, the min and max thresholds are required for the **TemperatureControl** trait: 

<html>
<body>

Attributes | Type | Description
-- | -- | --
temperatureRange | Object | Required.<br>Supported temperature range of the device.
minThresholdCelsius | Number | Required.<br>Minimum temperature for the range, in degrees Celsius.
maxThresholdCelsius | Number | Required.<br>Maximum temperature for the range, in degrees Celsius.

</body>
</html>

**Comment by robnielsen** [comment]
Here's an example for my ecobee remotes sensor:
![Screenshot (Jan 1, 2023 9_25_26 AM)](https://user-images.githubusercontent.com/838221/210176289-5ffd637d-f607-4f9e-9b3a-12e1fe0a16b3.png)
![Screenshot (Jan 1, 2023 9_25_51 AM)](https://user-images.githubusercontent.com/838221/210176290-33d2544f-c502-4096-87d3-25cc3e1d757e.png)

**Comment by michikrug** [comment]
Thanks for reporting. Will create a PR to implement this.

**Comment by michikrug** [comment]
@robnielsen Unfortunately, still with my changes implemented, the Google Home App does not provide any UI for the sensor and just shows its info screen.

Maybe Google relies for sensors on the devices to update their state in the home graph automatically to show a UI, which openHAB is currently not able to do.

**Comment by robnielsen** [comment]
@michikrug, This confirms what you are experiencing: https://issuetracker.google.com/issues/244185535

I wonder if ecobee is using the trait TemperatureSetting with the sensor instead of TemperatureControl?

**Comment by robnielsen** [comment]
@michikrug, when I ask Google Assistant "what is the temperature upstairs", it responds "It's currently 66 and Upstairs is off".

**Comment by michikrug** [comment]
> @michikrug, This confirms what you are experiencing: [issuetracker.google.com/issues/244185535](https://issuetracker.google.com/issues/244185535)
> 
> I wonder if ecobee is using the trait TemperatureSetting with the sensor instead of TemperatureControl?

Haha, indeed. Just tested it with `TemperatureSetting` and exactly the same view as in your screenshot appeared. :D

**Comment by michikrug** [comment]
@robnielsen I just created #432 to switch to the other trait. Will close the other PR #428 as it did not fix the sensor.

**Comment by robnielsen** [comment]
![PXL_20230105_183126758 - Copy](https://user-images.githubusercontent.com/838221/211156069-8381b36f-20c3-4d91-909a-4b79f72eef06.jpg)
