### ISSUE TITLE
Groups of switches

### ISSUE THREAD

**Issue by PatrickSteiner** [openhab/openhab-google-assistant#43]
Not sure if this is a problem on my side or a general one. This is what I did

default.items
Group:Switch:OR(ON,OFF) Wohnzimmer_Gruppe "Living Room Lights" <poweroutlet> ["Lighting"]
Switch Light_Wohnzimmer_Stehlampe "Stehlampe" <poweroutlet> (Wohnzimmer_Gruppe) ["Lighting"] { channel="..." }
Switch Light_Wohnzimmer_Klavierlampe "Klavierlampe" <poweroutlet> (Wohnzimmer_Gruppe) ["Lighting"] { channel="..." }

default.sidemap
sitemap default label="Zuhause"
{
    Switch item=Light_Wohnzimmer_Stehlampe label="Stehlampe"
    Switch item=Light_Wohnzimmer_Klavierlampe label="Klavierlampe"

    Switch item=Wohnzimmer_Gruppe label="Alle Lampen im Wohnzimmer"
}

What's happening is that I see the Switches and the Group via myopenhab.org but in the Google Assistant App I only see the Switches but not the Group.

Open for suggestions or hints.

**Comment by marziman** [comment]
Closing this..

**Comment by dpositive** [comment]
So what is the solution?

**Comment by michikrug** [comment]
There is a fix in the code - I can not tell you if the fix is already live and available

**Comment by dpositive** [comment]
I've tried today to add the Group into Google Assistant App but it doesn't see it

my item is:
Group:Switch:OR(ON,OFF) gBedroom_Switch ["Lighting"].

Do you have any idea how can I turn on/off the hole group of switches with Google Assistan voice command?
