### ISSUE TITLE
Support Sensors with both Google Nest Hub and Google Home app

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-google-assistant#440]
Prior to https://github.com/openhab/openhab-google-assistant/pull/432, Sensor data would show up on the Google Nest Hub and not in the Google Home app. Now sensor data shows up in the Google Home app, but not the Google Nest Hub. This request is to support both at the same time.

The Google Nest Hub used to look like this:

![211156117-a2b8728f-5c46-42e3-941a-6fcf14ecdd3a](https://user-images.githubusercontent.com/838221/212763706-cf167626-aa5e-4600-a761-990de11fbe63.jpg)

Now it looks like this:

![PXL_20230116_205003284](https://user-images.githubusercontent.com/838221/212764053-cc509d8c-ecd6-480b-ab2c-4c5ff17749df.jpg)

**Comment by michikrug** [comment]
God damn... Google should get their stuff working. 😖😣

Sorry for the inconvenience.

I probably should get a Nest Hub to test this in advance.

**Comment by michikrug** [comment]
Just ordered a Nest Hub... 💵

**Comment by michikrug** [comment]
Nest Hub arrived... did some testing.

-> #442
