### ISSUE TITLE
[Issue] HumiditySensor not working as expected on iOS

### ISSUE THREAD

**Issue by sindalschmidt** [openhab/openhab-google-assistant#448]
### Issue

- The HumiditySensor is not present in the OpenHAB UI selection of sensors.

- If circumvented by typing HumiditySensor into the code tab, the sensor will show up in Google Home, but no humidity value is present. Only tested on iOS. This works with the TemperatureSensor.
![IMG_2186](https://user-images.githubusercontent.com/44070556/219481159-7a770c2d-1e9a-443b-8b63-53af2164eb3b.PNG)

- If using the humidity item as part of a ClimateSensor together with a temperature sensor, only the temperature is shown. Asking Google about the humidity also fails.

**Comment by michikrug** [comment]
Hello and thanks for reaching out.

Some comments regarding your reports:

1) The missing selection in the openHAB UI is already implemented and "just" needs a new openHAB release as the UI is always shipped with the main package
2) That is really strange. For me it works both on Google Home on Android, Google Nest Hub and via Google Assistant both in German and English. Are you using a different language (just guessing from your device name...)? What does Google tell you when asking for the humidity? What kind of item did you use for it?

**Comment by diRk262** [comment]
Hi,
I am facing the same issue.
Adding the HumiditySensor via code tab shows the sensor in Google Home on Android, but no value for it.
The humnidity value in openhab is a number item, so this should work.
Language is german.

Code:
`value: HumiditySensor
config: {}
`
![GA](https://user-images.githubusercontent.com/76136884/219647606-da4091a8-f48d-4f0a-b511-076e351bac58.PNG)

![OH2](https://user-images.githubusercontent.com/76136884/219647931-79030b10-e4bb-4ce4-96ce-c2868a5d1449.PNG)

![OH](https://user-images.githubusercontent.com/76136884/219647625-1444aedd-5798-435e-a09d-939876f563d0.PNG)

**Comment by michikrug** [comment]
Thanks for the info.

Will do some more investigating...

**Comment by michikrug** [comment]
I guess I found the issue. Google is expecting Integer values, currently I hand over floating point values. Will provide a potential fix asap.

**Comment by michikrug** [comment]
Could you please retest?

**Comment by diRk262** [comment]
![Screenshot_20230221_203301_Home](https://user-images.githubusercontent.com/76136884/220441840-5bd0c815-766b-428a-a510-3684fa85e365.jpg)

Looks very good.
Thank you for the fix!
