### ISSUE TITLE
Something went wrong. Try again.

### ISSUE THREAD

**Issue by chriswalker01** [openhab/openhab-google-assistant#46]
Hi,

I had this working but recently had to rebuild the server running my instance of Openhab Cloud. I have not made any changes to my cloud function or Openhab server since it was last working.

I now can't get it working again. I've updated the database as per the instructions. I believe this is all I need to do as the cloud function is already set up.

In home control, I add my app, which is in testing mode, and am asked to 'allow' the connection. I hit allow and it says "Accounts now linked".

In then returns me to my device list and appears to be refreshing, but a few seconds later I get an error message that says, "Something went wrong. Try again.

In Openhab Cloud, I can see the application listed with a timestamp that I approved it.

Openhab is online and I can view the site maps.

Can anyone think of anything that could be causing this?

I'm using the iOS app.

**Comment by chriswalker01** [comment]
I'm still struggling to get this working again. I decided to start from scratch and created a new gcp project. All went smoothly until "testing" it in the Google Home app.
After selecting my test app in Google Home, logging in and choosing allow; I get a message that says "accounts now linked". A few seconds after that, a message pops up on the screen saying, "something went wrong, try again".
If I try again, Openhab asks me to "allow" the app again. Each time I do this another entry appears in the My Applications section of Openhab Cloud.
As mentioned previously, I had this working before rebuilding my server. Since then both the original gcp project and new one are showing exactly the same error.

**Comment by chriswalker01** [comment]
Interestingly, I just tried to use the official myopenhab.org website and I'm getting the same behaviour. Is this currently working for anyone else?

**Comment by tulamidan** [comment]
Most likely sth. i your items file. I'd try and work my way up with a limited amount of items. The google assistant is very tempramental when it comes to whitespaces or any character slightly misplaced

**Comment by chriswalker01** [comment]
Thanks tulamidan. I bit the bullet and moved items file in out and of the items folder and sure enough I narrowed it down to an item that had a typo in it. I didn't think I had made any changes to my items but apparently I had.

**Comment by drupol** [comment]
Hi,

sorry to dig up old topics, but I have the same issue. Could you explain how you did to fix this ?

Thanks

**Comment by chriswalker01** [comment]
It was a typo in my items file in Openhab. I think I had two items with the same description or something, so Google couldn't tell them apart.
