### ISSUE TITLE
Implement Fan

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-google-assistant#48]
Please implement the devices Fan (https://developers.google.com/actions/smarthome/guides/fan). I currently have my fans implemented as Switchable, and would be nice to have Google Home display them as their proper type.

**Comment by robnielsen** [comment]
My fans are only set up for on/off

**Comment by robnielsen** [comment]
This issue had both fan and outlet. Outlet has been implemented so I changed the issue to only indicate fan.

**Comment by theRealMCQwerty** [comment]
> I will look what I can do.
> For the Outlet it is simple.
> For the Fan, witch traits do you need?
> 
> * action.devices.traits.OnOff
> * action.devices.traits.FanSpeed
> * action.devices.traits.Modes
> * action.devices.traits.Toggles
> 
> OnOff and FanSpeed are enough I think?
> How many fan speeds are needed? slow, medium, high, auto?

I would appreciate fan support. @alibahba in answer to your question, OnOff and FanSpeed would be sufficient. As for speeds 'High', 'Medium' and 'Low' would be best. It would also be helpful if 'High' could have a synonym added 'Full'. 

Thank you!

**Comment by YuriyKu** [comment]
Hello,
Is there any updates when fan Google Assistant support will be available in openHab?
Thanks in advance.

**Comment by robnielsen** [comment]
Any updates on when this might be available?

**Comment by michikrug** [comment]
I implemented the Fan type on the PR #120 
https://github.com/openhab/openhab-google-assistant/pull/120/commits/94ee0fa2df4e2270a76d22fdb18eebf859f104b3

**Comment by robnielsen** [comment]
Verified that this works with latest update. Thanks for implementing.
