### ISSUE TITLE
Change default thermostat mode to 'off'

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-google-assistant#49]
With the latest update to the Google Home app, if you have a standalone thermometer, it will show it as heat mode, and you will be able to try and change the temp. This should be changed to 'off' do disable this behavior. 

The line that should be changed is:

`thermData.thermostatMode = "heat"; // doesn't matter, GA will only state the number (since we force Ambient and Setpoint to match)`

**Comment by Isaksson** [comment]
I guess this still is an issue?
I have a thermometer and have tagged it with `CurrentTemperature` but in Google Home app it displays as a Thermostat.
![screenshot_20181213-105219_home](https://user-images.githubusercontent.com/4119080/49932317-01fc6580-fec9-11e8-8e39-edadc9063172.jpg)

**Comment by julianjwong** [comment]
Another potentially related bug is that Google Nest Hub doesn't display the temperature like the Google Home App does. It tries to load the dial but says Current Mode Unsupported

**Comment by Isaksson** [comment]
I have not heard anything in 7 month I guess this is dead?

**Comment by michikrug** [comment]
As we now have `queryOnlyTemperatureSetting` for "read-only" Thermostats or even the `TemperatureSensor` for thermometer devices, this should be solved.
