### ISSUE TITLE
Could you please update readme file to reflect changes in Google (they removed Conversational Actions)

### ISSUE THREAD

**Issue by HuffYk** [openhab/openhab-google-assistant#492]
These commands in readme:

gactions update --action_package action.json --project <PROJECT ID>
gactions test --action_package action.json --project <PROJECT ID>

doesn't work. The conversational gactions client cannot authenticate to google anymore. Tool asks for authorization code and when clicking on generated URL, access is blocked with this error message "Access blocked: Assistant CLI’s request is invalid" because request is done with the out-of-band (OOB) flow which is not allowed anymore in Google.

**Comment by michikrug** [comment]
Thanks for letting us know.

Do you already have an updated flow at hand?

**Comment by HuffYk** [comment]
Well my expertise in all this is 1hour max :). I thought just readme is not updated as public https://myopenhab.org/ still works with google home and conversational actions were deprecated on June 13, 2023.  So I suppose there had to be some code change after 13.6. when this repo used conversational actions.

**Comment by michikrug** [comment]
OK. No worries.

I can just assure you that there has not been any change on this action regarding the discontinuation of conversational actions.

I guess creating an action only using the web ui might still work.
Nevertheless, I will have a look at the cli tooling

**Comment by michikrug** [comment]
As we are using a smart home action and not a conversational one, I guess we are not affected by the change.

**Comment by berni2288** [comment]
Hey @michikrug , did you already have a chance to look at the CLI tooling?
I also can't use gactions because Google doesn't allow the authentication from this tool anymore.
