### ISSUE TITLE
Requesting new Google Assistant class - Air conditioning unit

### ISSUE THREAD

**Issue by Kardiii** [openhab/openhab-google-assistant#576]
Hi!

I'm trying to implement my Daikin AC units in Openhab to be able to control them via the Google Assistant voice commands.
Unfortunately it is not possible to natively control and config the AC items, as there is no option to select.

According to Google Assistand it should be able to recognize AC units for a while.

https://developers.home.google.com/cloud-to-cloud/guides/acunit

Would you please check and add these option into Openhab?

**Comment by michikrug** [comment]
It is available now
