### ISSUE TITLE
States are not known - off Problem? 

### ISSUE THREAD

**Issue by Rar9** [openhab/openhab-google-assistant#6]
Goggle does not seem to know if a light is on / off.

I can only the same command "Turn on xyz" to also Turn Off my light off. 

 "Turn xyz Off"  is telling me thats its turning tbem off, but the light stays on

**Comment by marziman** [comment]
No thats a known issue.
Not sure if we need an extra issue for that?

**Comment by marziman** [comment]
I will keep it open to track it here..

**Comment by tdeckers** [comment]
I think this should be fixed when handleQueryAndExecute checks for intent and handles accordingly.  Now the function only implements logic for intent "action.devices.EXECUTE".  There should be a switch based on the value of request.body.inputs[0].intent.  If the value is "action.devices.EXECUTE" then do what's implemented today.  If the value is "action.devices.QUERY", then return current state (as obtained from Openhab) back to Google.
Ref: https://developers.google.com/actions/smarthome/traits/onoff#request
