### ISSUE TITLE
Google home - Brazilian portuguese

### ISSUE THREAD

**Issue by pabloalcantara** [openhab/openhab-google-assistant#62]
Brazilian portuguese is recently added to Google home. but myopenhab isn't underestending portuguese.
It's possible to add this language? How can i help with that?

**Comment by alibahba** [comment]
The translation is done by Google and openHAB has nothing to do with that.
The issue can be closed.

**Comment by pabloalcantara** [comment]
No. The assistant translations ia done by Google (the gHome assistant os aleready in portuguese), but the apps need to be adjusted to every New language Google adds to assustant

**Comment by alibahba** [comment]
You're wrong. This is not an Assistant app but a **Google Smart Home application**. We don't have to provide any translation. [Google documantation](https://developers.google.com/actions/smarthome/)

**Comment by marziman** [comment]
I am closing this, since openhab is not responsible for the language, rather than Google.
