### ISSUE TITLE
Implementation of ColorSetting

### ISSUE THREAD

**Issue by alibahba** [openhab/openhab-google-assistant#66]
For color lights, we use now the ColorSpectrum trait, but ColorSpectrum is deprecated.
There is a new trait ColorSetting witch must be used. It is possible to implement the color temperature in this new trait also.

**Comment by marziman** [comment]
Do you volunteer to touch this? Or do you want me to go on it?

**Comment by marziman** [comment]
I think this is not actual anymore?...Closing it. Lets create a new issue if needed
