### ISSUE TITLE
Will I need to update my Spark plan from firebase to plan Blaze?

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [openhab/openhab-google-assistant#70]
I've been trying to create an application with dialogflow that uses Firebase to communicate with the REST API of OpenHab2 (through myopenhab) and Firebase requires me to add a billing plan to communicate with external networks to Google.

**Comment by marziman** [comment]
I am closing this, as it is not related to the GA integration. Please consider asking such questions in the forum please. Many thanks for using openHAB!
