### ISSUE TITLE
Possible to use without openhab-cloud ?

### ISSUE THREAD

**Issue by lucacalcaterra** [openhab/openhab-google-assistant#71]
Hi !It is not clear to me.. whether it is possible to use it without the open-cloud cloud on self hosted   ?

Thanks,
Luca

**Comment by velaar** [comment]
It is possible if you use your own instance of openhab-cloud. This is how people are testing it.

**Comment by lucacalcaterra** [comment]
> It is possible if you use your own instance of openhab-cloud. This is how people are testing it.
I know this , but...
I want to know if it's possible to use Google Assistant Action directly on openhab instance without the cloud layer

**Comment by marziman** [comment]
Yes this is possible.

The cloud function runs on Google Cloud, but the fullfillment backend URL can be configured.

**Comment by marziman** [comment]
I will close it fornow, you can contact me in the openhab community forum. But it is not depending tightly to openhab cloud, but you need go adjust the restcalls and your rest backend.
