### ISSUE TITLE
Google Cloud function or Firebase ?

### ISSUE THREAD

**Issue by lucacalcaterra** [openhab/openhab-google-assistant#73]
I'm currently have an openhab instance with Gcloud function , deployed as README on this project.

Is possible to use Firebase functions ? Which are the differences between two ?

Thanks !

**Comment by marziman** [comment]
Hello @lucacalcaterra,

can you please use the community forum for these kind of questions?

Will close this here..

**Comment by lucacalcaterra** [comment]
Ok , sorry... Thanks !!
