### ISSUE TITLE
Native Support for Locks (e.g. no scenes / routines)

### ISSUE THREAD

**Issue by skimdankish** [openhab/openhab-google-assistant#75]
@marziman 

I have been successful at implementing "action.devices.traits.LockUnlock" for locks.  I have a Z-Wave Schlage BE469 which has a Switch type item for ON/OFF.

Since it is not even yet publicly advertised by Google yet I wanted to raise it here first to see if it's worth pushing or if it should wait.  The reason I ask is because they support August and some others...so why not publish the API??

Attached is the SmartHome schema I dug up online - seems pretty straightforward and it is...

If this will be well received I can prep for a push, I just need to right-size my commits as I have been "rogue" for many months since it's been smooth sailing.

~Ryan

[SmartHome LockUnlock Schema.pdf](https://github.com/openhab/openhab-google-assistant/files/2958145/SmartHome.LockUnlock.Schema.pdf)

**Comment by marziman** [comment]
Thanks I will take a look!

**Comment by mariusmu** [comment]
Any news on this?

**Comment by tnemrap** [comment]
Any news on this?

**Comment by skimdankish** [comment]
FYI, I haven't changed it since March though it has been working.  Google has since added it into production.  They tweaked it some with 2-factor authentication, I don't think OH2 supports this functionality - this could be challenging as well since there are Wifi, Zwave, Zigbee (?) locks that may use security differently.

**Comment by michikrug** [comment]
The issue here is, that openHAB itself does not support a item type "Lock"

**Comment by marziman** [comment]
done with https://github.com/openhab/openhab-google-assistant/pull/118
