### ISSUE TITLE
TypeError: smarthome is not a function

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab-google-assistant#79]
We are trying to implement Report State API, which we would like to share with the community.

Now we are getting below issue, which we could not resolve.

Could you please help us to resolve this issue ?

We have added below lines to openhab.js file
```

const {smarthome} = require('actions-on-google');
const app = smarthome({
});
```

Please find the below console output.

smartfueb_march_gmail_com@instance-1-ubuntu16:/home/smartfueb_march/openhab-google-assistant/functions$ gcloud beta functions deploy openhabGoogleAssistant --stage-bucket smart_test1 --trigger-http

```
Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.beta.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: smarthome is not a function
at Object.<anonymous> (/user_code/openhab.js:23:13)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/user_code/index.js:18:17)
at Module._compile (module.js:577:32)
```

**Comment by marziman** [comment]
Can we please shift this to the community forum. We did not implement ReportState yet.
So I cant really help. Maybe lets discuss this in the forum.

Thanks 
BR Mehmet
