### ISSUE TITLE
Thermostats do not work without no changes. 

### ISSUE THREAD

**Issue by fmalfatto** [openhab/openhab-google-assistant#85]
I have 2 thermostats, 6 lights and 4 blinds defined in Openhab, all working in paperui and basicui and also with remote app on smartphone.
I defined them  some time ago also in google assistant and they worked, at least only lights and thermostats. Blinds worked for a while then disappeared. But since yesterday, blinds appeared again in Home assistant but I cannot control them. At same time the two thermostats say "Non responding". I detached openhab from assistand and reconnect all the devices (it is a long job, it should be avoided at every change) but thermo do not work  in any way. No messages in logs.
Here is the things:
`Group Zona1 "Zona giorno" ["Thermostat"]
 String Z1_HCmode "Heat/cool" (Zona1)  [ "homekit:HeatingCoolingMode" ] { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:heatingCoolingMode"}
 Number:Temperature Z1_Temp  "Zona giorno [%.1f %unit%]" <temperature>  (Zona1) ["CurrentTemperature"] { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:temperature" }
 Number:Temperature Z1_target "Target T [%.1f %unit%]" <temperature> (Zona1) ["TargetTemperature"] { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:targetTemperature"}
 Number:Temperature Z1_ThSet "SetPoint T ext. [%.1f %unit%]" <temperature> (Zona1) { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:setpointTemperature"}
//
Group Zona2 "Zona notte" ["Thermostat"]
 String Z2_HCmode "Heat/cool" (Zona2) [ "homekit:HeatingCoolingMode" ] { channel="openwebnet:bus_thermostat:mhs1:Thermnotte:heatingCoolingMode"}
 Number:Temperature  Z2_Temp    "Zona notte [%.1f %unit%]"   <temperature>  (Zona2) ["CurrentTemperature"] { channel="openwebnet:bus_thermostat:mhs1:Thermnotte:temperature" }
 Number:Temperature Z2_target "Target T [%.1f %unit%]" <temperature> (Zona2) ["TargetTemperature"]  { channel="openwebnet:bus_thermostat:mhs1:Thermnotte:targetTemperature"}
 Number:Temperature Z2_ThSet "SetPoint T ext. [%.1f %unit%]" <temperature> (Zona2) { channel="openwebnet:bus_thermostat:mhs1:Thermnotte:setpointTemperature"}
`

**Comment by mvalla** [comment]
It looks like you assign the TargetTemperature tag to the wrong items, it should be added to items with the setPointTemperature channel like in the OpenWebNet README example.
(I admit these similar names create a bit of confusion...)

Probably it worked before because you modified the items file but later you did not do a “sync my devices”  in Google.

Correct the item file following the README example , restart openHAB and then do a sync my devices on Google.

If it works close this issue

In general before opening a new issue on GitHub ask for assistance in the main thread with your particular configuration.
Only when you are sure it’s a bug, issue a new bug on GitHub

**Comment by fmalfatto** [comment]
This is what I read: 
`If you expose thermostats make sure than you have:
A group item with the tag [ "Thermostat" ]
A number or string item with the tag [ "homekit:HeatingCoolingMode" ]
A number item with the tag [ "CurrentTemperature" ]
A number item with the tag [ "TargetTemperature" ]
Group g_HK_Basement_TSTAT "Basement Thermostat" [ "Thermostat", "Fahrenheit" ]
  Number HK_Basement_Mode "Basement Heating/Cooling Mode" (g_HK_Basement_TSTAT) [ "homekit:HeatingCoolingMode" ]
  Number HK_Basement_Temp "Basement Temperature" (g_HK_Basement_TSTAT) [ "CurrentTemperature" ]
  Number HK_Basement_Setpoint "Basement Setpoint" (g_HK_Basement_TSTAT) [ "TargetTemperature" ]`

So I coupled the tag with the same channel name ... because channels are not reported.

Now I changed to:
'Group Zona1 "Zona giorno" <heating> [ "Thermostat" ]
 String Z1_HCmode "Heat/cool" (Zona1)  [ "homekit:HeatingCoolingMode" ] { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:heatingCoolingMode"}
 Number:Temperature Z1_Temp  "Zona giorno [%.1f %unit%]" <temperature>  (Zona1) ["CurrentTemperature"] { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:temperature" }
 Number:Temperature Z1_target "Target T [%.1f %unit%]" <temperature> (Zona1) { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:targetTemperature"}
 Number:Temperature Z1_ThSet "SetPoint T ext. [%.1f %unit%]" <temperature> (Zona1)  ["TargetTemperature"] { channel="openwebnet:bus_thermostat:mhs1:Thermgiorno:setpointTemperature"}'

But nothing changed after restarting and resyncing several times.

Relating to syncying I must sync my devices every 2/3 days because they stop working, so I can exclude that I was working with old configurations.
The only changed thing is the Home app on smartphone, it was updated around May 10th. .
For this reason I close this issue and switch off from chats, waiting for end of works! TY again
