### ISSUE TITLE
Not being able to link

### ISSUE THREAD

**Issue by jblancoperez** [openhab/openhab-google-assistant#9]
Hello,

I have a personal openhab-cloud server.

I have created the function, registerer a new Oauth client and scope in my cloud.
I  am able to login and grant access to google assistant on my cloud.

When finishing the acocunt linking, I received " couldn't update setting. please check your connection " diaglog box and cannot see any items.

Looking in the cloud function log, I can see items being synced, But on new device appears in my android app.

Anybody seeing any similar thing?

Thanks a lot for the initial code!!

**Comment by sk8ter** [comment]
I also created the function, tried to setup Oauth for "Account linking" but configuration is not quite correct. I see my app in the "Add devises" list, but then when I try to add, it redirects to myopenhab which shows: "Forbidden".

**Comment by marziman** [comment]
Hi,
@jblancoperez,
the first topic is not an oh-google assistant issue. It is a problem which google needs to solve.
Please use the community.openhab.org for questions and not github issues.
Please provide your infos and detailed logs there.

Thx!

**Comment by marziman** [comment]
@sk8ter,
it is pretty not possible to understand what you re trying to do if you just write 1-2 sentences. You cannot link your private function to the official myopenhab.org.
Please describe at the forum detailed whats the state and I can try to help.
What I saw there didnt help me to understand your approach.

**Comment by marziman** [comment]
Closing this...
