### ISSUE TITLE
items with multiple tags cause Google Assistant to discover no devices

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-google-assistant#91]
When trying to link Google Assistant with openHAB, in case openHAB has items with multiple tags (`[ "Blinds" , "Switchable"  ] `) , account linking is completed, but no device will be discovered by Google Assistant.

## Expected Behavior
In case an item has multiple tags, the first supported tag is selected

## Current Behavior
No error is reported and device discovery fails

## Possible Solution
In case multiple tags are present, choose the first supported one (if any). 
Or return to the linking process a meaningful message (to be checked if it gets displayed in the GA app)

## Steps to Reproduce (for Bugs)
1. item configuration with at least 1 item with multiple tags, for example:
`Rollershutter  myShutter       "Shutter [%.0f %%]"      <rollershutter>  (gShutters)     [ "Blinds" , "Switchable"  ]  { channel="xxxxxxxxxxxxxxxxxxxx" }`
1. from Google Assistant app start account linking to openHAB
1. account is linked but no devices are found (the app reports briefly a message "Something went wrong, try again")

**Comment by michikrug** [comment]
Should not be a problem anymore
