### ISSUE TITLE
Bidirectional commands to Google

### ISSUE THREAD

**Issue by pmknowles** [openhab/openhab-google-assistant#97]
Not really an issue but something I'd like to be able to do.
I have Routines in Google Assistant to do stuff and Rules in openHAB.
I can get openHAB (using the Chromecast binding) to play a door bell sound on my Google minis when someone presses the door bell and I can get Google to switch on lights controlled by openHAB.
I'd like all my rules to be in one place - openHAB and, for example,
I'd like to be able to get Google to stream a radio programme when something happens in openHAB.
It may be possible already but I haven't seen a method of doing it.

**Comment by marziman** [comment]
Then this shall go to the openHAB community forum and not an issue.
